import type { EventType, EmotionalIntensity } from "./constants"
import type { ObservationEvent } from "@/types/event"

export type { ObservationEvent }

/** Mock data for development. Uses closed domain types. */
export const EVENTS: ObservationEvent[] = [
  {
    id: "e01",
    title: "La última vez que dormí sin recordar",
    type: "DEATH",
    intensity: "5",
    date: "2021-03-14",
    excerpt: "Había una claridad extraña en el aire, como si el tiempo hubiera decidido detenerse.",
    description:
      "Había una claridad extraña en el aire, como si el tiempo hubiera decidido detenerse justo antes de que yo lo notara. No hubo señal. Solo el momento antes y el momento después, irreversiblemente distintos.",
    location: "Ciudad de México, Colonia Roma",
    coords: { lat: 19.4194, lng: -99.1567 },
    tags: ["sueño", "umbral", "silencio"],
  },
  {
    id: "e02",
    title: "El grieta en la pared del cuarto viejo",
    type: "ACCIDENT",
    intensity: "3",
    date: "2019-08-22",
    excerpt: "No era la grieta lo que me perturbaba, sino lo que imaginaba al otro lado.",
    description:
      "No era la grieta lo que me perturbaba, sino lo que imaginaba al otro lado. Una apertura que no debería existir, un testimonio mudo de que las cosas se rompen sin pedir permiso.",
    location: "Oaxaca, Centro Histórico",
    coords: { lat: 17.0669, lng: -96.7234 },
    tags: ["fractura", "espacio", "infancia"],
  },
  {
    id: "e03",
    title: "El hilo que conectaba dos conversaciones",
    type: "RELATIONSHIP_END",
    intensity: "1",
    date: "2022-11-05",
    excerpt: "Alguien dijo algo que resonó con algo dicho meses antes por alguien completamente diferente.",
    description:
      "Alguien dijo algo que resonó con algo dicho meses antes por alguien completamente diferente. El hilo invisible entre ambas frases se tensó, vibró, y se cortó cuando quise atraparlo.",
    location: "Buenos Aires, San Telmo",
    coords: { lat: -34.6218, lng: -58.3703 },
    tags: ["lenguaje", "coincidencia", "memoria"],
  },
  {
    id: "e04",
    title: "La puerta que no volví a abrir",
    type: "MAJOR_DECISION",
    intensity: "5",
    date: "2020-06-30",
    excerpt: "Estaba ahí, esperando. Yo también. Ninguno cedió.",
    description:
      "Estaba ahí, esperando. Yo también. Ninguno cedió. Esa puerta sigue ahí en algún lugar de mi cartografía interior, siempre entreabierta, siempre sin cruzar.",
    location: "Madrid, Lavapiés",
    coords: { lat: 40.4084, lng: -3.7009 },
    tags: ["decisión", "umbral", "irreversibilidad"],
  },
  {
    id: "e05",
    title: "Cuando la vela se apagó sola",
    type: "DEATH",
    intensity: "3",
    date: "2023-02-01",
    excerpt: "No había corriente de aire. Simplemente se fue.",
    description:
      "No había corriente de aire. Simplemente se fue. Quedamos a oscuras los tres, y nadie habló por un tiempo que se sintió más largo de lo que fue.",
    location: "Guadalajara, Tlaquepaque",
    coords: { lat: 20.6337, lng: -103.3117 },
    tags: ["luz", "silencio", "presencia"],
  },
  {
    id: "e06",
    title: "La fractura en la cerámica",
    type: "ACCIDENT",
    intensity: "1",
    date: "2018-05-17",
    excerpt: "Kintsugi, decían. Pero a veces las roturas simplemente son roturas.",
    description:
      "Kintsugi, decían. Pero a veces las roturas simplemente son roturas, sin metáfora redentora. Esta taza se rompió y ya no existe de la misma forma. Eso es todo.",
    location: "Kyoto",
    coords: { lat: 35.0116, lng: 135.7681 },
    tags: ["objeto", "pérdida", "materia"],
  },
  {
    id: "e07",
    title: "El hilo rojo de las coincidencias",
    type: "RELATIONSHIP_END",
    intensity: "5",
    date: "2024-01-18",
    excerpt: "Tres veces el mismo número en tres días distintos. No creo en señales, pero las anoto.",
    description:
      "Tres veces el mismo número en tres días distintos. No creo en señales, pero las anoto. El hilo rojo entre ellas lo tejí yo, lo sé, pero tejido ya, no se puede destejer.",
    location: "Lisboa, Alfama",
    coords: { lat: 38.7147, lng: -9.1327 },
    tags: ["numerología", "patrón", "interpretación"],
  },
  {
    id: "e08",
    title: "La puerta de la casa que ya no existe",
    type: "RELOCATION",
    intensity: "3",
    date: "2017-09-09",
    excerpt: "Demolieron el edificio. La puerta debe estar en algún vertedero.",
    description:
      "Demolieron el edificio. La puerta debe estar en algún vertedero, convertida en astillas. Pero en mi mapa sigue estando ahí, en sus coordenadas originales, esperando una mano.",
    location: "Montevideo, Ciudad Vieja",
    coords: { lat: -34.9058, lng: -56.1913 },
    tags: ["arquitectura", "desaparición", "nostalgia"],
  },
  {
    id: "e09",
    title: "La vela de todos los velatorios",
    type: "DEATH",
    intensity: "5",
    date: "2015-12-20",
    excerpt: "Se enciende siempre la misma llama, aunque cambie quien la sostenga.",
    description:
      "Se enciende siempre la misma llama, aunque cambie quien la sostenga. He visto encender velas por personas muy distintas, y siempre es el mismo gesto, el mismo silencio al bajar la cerilla.",
    location: "Sevilla, Triana",
    coords: { lat: 37.3812, lng: -6.0022 },
    tags: ["ritual", "muerte", "continuidad"],
  },
  {
    id: "e10",
    title: "Grieta en el tiempo",
    type: "ACCIDENT",
    intensity: "5",
    date: "2022-07-07",
    excerpt: "Un momento en que el presente se rompió y pude ver el pasado y el futuro al mismo tiempo.",
    description:
      "Un momento en que el presente se rompió y pude ver simultáneamente lo que había sido y lo que sería. Duró apenas un segundo. Pero ese segundo tiene coordenadas propias en mi mapa.",
    location: "Patagonia",
    coords: { lat: -42.7692, lng: -65.0381 },
    tags: ["tiempo", "visión", "grieta temporal"],
  },
  {
    id: "e11",
    title: "El hilo que ata la infancia a este momento",
    type: "RELATIONSHIP_END",
    intensity: "1",
    date: "2024-08-03",
    excerpt: "Un olor. Solo un olor. Y de repente tenía ocho años.",
    description:
      "Un olor. Solo un olor, el de la lluvia sobre tierra caliente. Y de repente tenía ocho años, estaba en el patio de casa, y el hilo que une ese niño con quien soy ahora se tensó con una claridad que casi dolió.",
    location: "Veracruz",
    coords: { lat: 19.1771, lng: -96.1332 },
    tags: ["olfato", "infancia", "involuntario"],
  },
  {
    id: "e00",
    title: "En el vestíbulo de Bellas Artes",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "2023-09-15",
    excerpt: "Mirando hacia el techo antes de entrar. La decisión de cruzar o no.",
    description:
      "Estaba en el vestíbulo del Palacio de Bellas Artes, mirando hacia el techo antes de entrar a la función. En ese momento supe que cruzar o no cruzar esa puerta cambiaría algo. No sabía qué. Entré.",
    location: "Ciudad de México, Centro Histórico, cerca de Bellas Artes",
    coords: { lat: 19.4353, lng: -99.1413 },
    tags: ["umbral", "arte", "centro"],
  },
  {
    id: "e12",
    title: "La puerta entreabierta al amanecer",
    type: "MAJOR_DECISION",
    intensity: "1",
    date: "2023-06-21",
    excerpt: "Alguien la dejó así. No sé si fue un descuido o una invitación.",
    description:
      "Alguien la dejó así, entreabierta, a las cinco y media de la mañana. No sé si fue un descuido o una invitación. Me quedé mirando la franja de luz sin entrar. Hay umbrales que se respetan.",
    location: "Cartagena de Indias",
    coords: { lat: 10.391, lng: -75.4794 },
    tags: ["amanecer", "umbral", "espera"],
  },
  {
    id: "e13",
    title: "Descubrimiento de La Ogresa de la Roma",
    type: "DEATH",
    intensity: "5",
    date: "1941-04-01",
    excerpt: "Se destapa la macabra red de tráfico de menores operada por Felícitas Sánchez Neyra.",
    description:
      "Se destapa la macabra red de tráfico de menores operada por Felícitas Sánchez Neyra. La policía encontró cráneos y restos de bebés calcinados o arrojados al drenaje en su pensión de la colonia Roma.",
    location: "Salamanca 9, Colonia Roma, Cuauhtémoc, CDMX",
    coords: { lat: 19.4215, lng: -99.1678 },
    tags: ["crimen real", "asesino en serie", "oscuridad", "colonia roma"],
  },
  {
    id: "e14",
    title: "Arresto de El Estrangulador de Tacuba",
    type: "DEATH",
    intensity: "5",
    date: "1942-09-01",
    excerpt: "Captura de Gregorio Cárdenas Hernández tras múltiples homicidios en Tacuba.",
    description:
      "Captura de Gregorio Cárdenas Hernández, un brillante estudiante de química que estranguló a cuatro mujeres, incluyendo a su novia, enterrándolas en el jardín de su casa en Tacuba. Se convirtió en un fenómeno mediático.",
    location: "Calle Mar del Norte, Tacuba, Miguel Hidalgo, CDMX",
    coords: { lat: 19.4583, lng: -99.1861 },
    tags: ["crimen real", "psicopatía", "tacuba", "nota roja"],
  },
  {
    id: "e15",
    title: "Suicidio en la Posada del Sol",
    type: "DEATH",
    intensity: "4",
    date: "1945-01-01",
    excerpt: "El arquitecto Francisco Saldaña Galván aparece muerto en su obra inacabada.",
    description:
      "El arquitecto Francisco Saldaña Galván, acorralado por las deudas y la presión de construir un monumental y esotérico hotel-manicomio que fusionaba masonería y arte gótico, se ahorca en el campanario de su obra inacabada.",
    location: "La Posada del Sol, Niños Héroes 139, Cuauhtémoc, CDMX",
    coords: { lat: 19.4217, lng: -99.1492 },
    tags: ["arquitectura", "esoterismo", "fantasma", "ruinas urbanas"],
  },
  {
    id: "e16",
    title: "El Baile de los 41",
    type: "LEGAL_EVENT",
    intensity: "4",
    date: "1901-11-17",
    excerpt: "Redada policial en un baile privado que derivó en uno de los mayores escándalos del Porfiriato.",
    description:
      "Redada policial secreta en una mansión de la colonia Tabacalera donde se celebraba un baile de hombres de la alta sociedad, la mitad vestidos de mujer. Se rumora que el participante 42, yerno de Porfirio Díaz, fue encubierto.",
    location: "Calle de la Paz (hoy Ezequiel Montes), Cuauhtémoc, CDMX",
    coords: { lat: 19.4355, lng: -99.1533 },
    tags: ["homosexualidad", "porfiriato", "escándalo", "policía"],
  },
  {
    id: "e17",
    title: "El robo del siglo en el Museo de Antropología",
    type: "LEGAL_EVENT",
    intensity: "4",
    date: "1985-12-25",
    excerpt: "Dos estudiantes saquearon 140 piezas del museo durante la madrugada de Navidad.",
    description:
      "Aprovechando la falta de vigilancia en Navidad, dos estudiantes de veterinaria saltan la barda del museo y saquean 140 piezas invaluables, incluyendo la máscara de jade del Dios Murciélago.",
    location: "Museo Nacional de Antropología, Miguel Hidalgo, CDMX",
    coords: { lat: 19.426, lng: -99.1863 },
    tags: ["robo", "artefactos", "historia criminal", "arqueología"],
  },
  {
    id: "e18",
    title: "Operación Castañeda (Cierre del manicomio)",
    type: "RELOCATION",
    intensity: "4",
    date: "1968-06-29",
    excerpt: "Cierre definitivo de La Castañeda y traslado masivo de pacientes psiquiátricos.",
    description:
      "Demolición y cierre definitivo del Manicomio General 'La Castañeda'. Los miles de pacientes, hacinados y maltratados durante décadas, fueron trasladados a granjas psiquiátricas modernas bajo un operativo cuasi militar.",
    location: "Manicomio La Castañeda, Mixcoac, Álvaro Obregón, CDMX",
    coords: { lat: 19.3752, lng: -99.1883 },
    tags: ["psiquiatría", "locura", "ruinas urbanas", "instituciones"],
  },
  {
    id: "e19",
    title: "Arresto del Caníbal de la Guerrero",
    type: "DEATH",
    intensity: "5",
    date: "2007-10-08",
    excerpt: "La policía halló evidencia de homicidio y desmembramiento en un departamento de la colonia Guerrero.",
    description:
      "La policía irrumpe en el departamento de José Luis Calva Zepeda, un poeta y novelista frustrado de estética oscura. Hallaron a su pareja descuartizada en un clóset y carne humana guisándose con limón en la estufa.",
    location: "Mosqueta 198, Colonia Guerrero, Cuauhtémoc, CDMX",
    coords: { lat: 19.4442, lng: -99.1415 },
    tags: ["canibalismo", "asesino en serie", "poeta maldito", "macabro"],
  },
  {
    id: "e20",
    title: "Primer altar público a la Santa Muerte",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "2001-10-31",
    excerpt: "Se instala en Tepito el primer santuario callejero visible de la Santa Muerte.",
    description:
      "Enriqueta Romero (Doña Queta) saca una estatua de tamaño real de la Santa Muerte a la acera de su casa en Tepito. Se convierte en el primer santuario callejero de este culto subterráneo, congregando a miles de marginados.",
    location: "Alfarería 12, Tepito, Cuauhtémoc, CDMX",
    coords: { lat: 19.4459, lng: -99.1245 },
    tags: ["ocultismo", "religión popular", "tepito", "folclore oscuro"],
  },
  {
    id: "e21",
    title: "Descubrimiento de los huesos de Hernán Cortés",
    type: "MAJOR_DECISION",
    intensity: "3",
    date: "1946-11-24",
    excerpt: "Historiadores redescubren y autentican en secreto los restos de Hernán Cortés.",
    description:
      "Tras más de un siglo de permanecer escondidos en un muro para evitar la furia popular, un grupo de historiadores desentierra en secreto los restos de Cortés en el Hospital de Jesús para autenticarlos y devolverlos al nicho.",
    location: "Iglesia de Jesús Nazareno, Cuauhtémoc, CDMX",
    coords: { lat: 19.4287, lng: -99.1332 },
    tags: ["secretos", "conquistador", "huesos", "misterio histórico"],
  },
  {
    id: "e22",
    title: "Asesinato del Gral. Álvaro Obregón en La Bombilla",
    type: "DEATH",
    intensity: "5",
    date: "1928-07-17",
    excerpt: "El presidente electo fue asesinado durante un banquete en San Ángel.",
    description:
      "El presidente electo Obregón es asesinado durante un banquete en el restaurante La Bombilla por José de León Toral, un fanático cristero que fingió ser dibujante de caricaturas para acercarse a su mesa y dispararle a quemarropa.",
    location: "Parque de la Bombilla, Álvaro Obregón, CDMX",
    coords: { lat: 19.3444, lng: -99.1866 },
    tags: ["magnicidio", "fanatismo", "revolución", "traición"],
  },
  {
    id: "e23",
    title: "Choque de trenes del Metro Viaducto",
    type: "ACCIDENT",
    intensity: "5",
    date: "1975-10-20",
    excerpt: "Un convoy impactó a otro en Viaducto, dejando decenas de fallecidos.",
    description:
      "El accidente más fatal en la historia del STC Metro (antes de la Línea 12). Un tren alcanzó a otro estacionado en Viaducto a casi 70 km/h debido a una supuesta falla en el pilotaje automático, dejando más de 30 muertos.",
    location: "Estación Metro Viaducto (Línea 2), Iztacalco, CDMX",
    coords: { lat: 19.4009, lng: -99.1357 },
    tags: ["desastre", "metro", "accidente", "maquinaria"],
  },
  {
    id: "e24",
    title: "El sismo que derribó al Ángel",
    type: "ACCIDENT",
    intensity: "4",
    date: "1957-07-28",
    excerpt: "Un terremoto derribó la escultura del Ángel de la Independencia.",
    description:
      "Un terremoto de magnitud 7.9 sacude la ciudad en la madrugada, provocando la aparatosa caída de la estatua de la Victoria Alada desde la cima del Monumento a la Independencia. La cabeza rodó por el pavimento.",
    location: "Paseo de la Reforma, Colonia Juárez, Cuauhtémoc, CDMX",
    coords: { lat: 19.427, lng: -99.1676 },
    tags: ["terremoto", "ruina simbólica", "monumento", "desastre natural"],
  },
  {
    id: "e25",
    title: "Incendio del Lobohombo",
    type: "ACCIDENT",
    intensity: "5",
    date: "2000-10-20",
    excerpt: "Un incendio en el antro Lobohombo dejó víctimas por salidas bloqueadas.",
    description:
      "El antro caribeño más grande y ostentoso de la ciudad, tapizado de materiales inflamables ilegales, arde de madrugada. Las salidas de emergencia estaban cerradas con candado. Murieron 22 personas calcinadas o asfixiadas.",
    location: "Insurgentes Norte 32 (Av. Antonio Caso), Cuauhtémoc, CDMX",
    coords: { lat: 19.4352, lng: -99.1578 },
    tags: ["fuego", "corrupción", "tragedia", "vida nocturna"],
  },
  {
    id: "e26",
    title: "Aparición de los monolitos en Metro Talismán",
    type: "NEW_BEGINNING",
    intensity: "2",
    date: "1978-01-01",
    excerpt: "Durante obras del Metro se hallaron restos fósiles de mamut en Talismán.",
    description:
      "Durante las excavaciones profundas para la construcción de la Línea 4, los ingenieros desentierran los restos fosilizados de un mamut del Pleistoceno, evidenciando la megafauna que habitaba el lago primigenio.",
    location: "Estación Metro Talismán, Gustavo A. Madero, CDMX",
    coords: { lat: 19.4682, lng: -99.1098 },
    tags: ["paleontología", "mamut", "subterráneo", "metro"],
  },
  {
    id: "e27",
    title: "Fusilamiento del Padre Pro",
    type: "DEATH",
    intensity: "4",
    date: "1927-11-23",
    excerpt: "Miguel Agustín Pro fue ejecutado sin juicio en un acto de escarmiento político.",
    description:
      "El sacerdote jesuita Miguel Agustín Pro es fusilado sin juicio previo por órdenes del presidente Plutarco Elías Calles, acusado falsamente de atentar contra Álvaro Obregón. Murió con los brazos en cruz gritando '¡Viva Cristo Rey!'.",
    location: "Comandancia de Policía (Lotería Nacional actual), Cuauhtémoc, CDMX",
    coords: { lat: 19.4357, lng: -99.1491 },
    tags: ["ejecución", "cristeros", "mártir", "política"],
  },
  {
    id: "e28",
    title: "Captura de Juana Barraza, La Mataviejitas",
    type: "LEGAL_EVENT",
    intensity: "5",
    date: "2006-01-25",
    excerpt: "Juana Barraza fue detenida tras años de homicidios contra mujeres adultas mayores.",
    description:
      "Juana Barraza fue detenida en la alcaldía Iztapalapa tras ser sorprendida huyendo de la escena de un homicidio. Se le atribuyeron múltiples asesinatos de mujeres adultas mayores cometidos entre 1998 y 2006. El caso generó pánico social y fuertes críticas a la investigación inicial, que perfilaba erróneamente al agresor como hombre.",
    location: "Colonia Moctezuma Segunda Sección, Venustiano Carranza, CDMX",
    coords: { lat: 19.4308, lng: -99.0986 },
    tags: ["nota roja", "asesinatos seriales", "pánico social"],
  },
  {
    id: "e29",
    title: "Descubrimiento de los cuerpos enterrados por Gregorio Cárdenas en Tacuba",
    type: "DEATH",
    intensity: "5",
    date: "1942-01-01",
    excerpt: "Se hallaron cuerpos enterrados en el domicilio de Gregorio Cárdenas en Tacuba.",
    description:
      "Gregorio 'Goyo' Cárdenas, estudiante de química, confesó y fue vinculado con el asesinato de varias mujeres cuyos cuerpos fueron hallados enterrados en el patio de su domicilio en Tacuba. El caso conmocionó a la opinión pública y fue ampliamente cubierto por la prensa como ejemplo de doble vida y desviación psicológica.",
    location: "Tacuba, Miguel Hidalgo, CDMX",
    coords: { lat: 19.4595, lng: -99.187 },
    tags: ["asesino serial", "tacuba", "nota roja histórica"],
  },
  {
    id: "e30",
    title: "Leyenda urbana de la Tamalera de la muerte",
    type: "DEATH",
    intensity: "3",
    date: "1980-01-01",
    excerpt: "En los años ochenta circuló el rumor de una tamalera que usaba carne humana.",
    description:
      "Durante la década de 1980 circuló en colonias del oriente de la Ciudad de México el rumor de una vendedora de tamales que utilizaba carne humana en sus productos. No existen registros judiciales que confirmen el hecho, pero la historia se difundió en medios sensacionalistas y generó desconfianza y alarma entre vecinos.",
    location: "Zona oriente, Iztapalapa, CDMX",
    coords: { lat: 19.3569, lng: -99.062 },
    tags: ["leyenda urbana", "rumor", "pánico moral"],
  },
  {
    id: "e31",
    title: "Milagro médico en el Hospital Juárez",
    type: "HEALTH_DIAGNOSIS",
    intensity: "4",
    date: "1952-05-14",
    excerpt: "Una joven con polio bulbar logró respirar por sí misma tras meses en pulmón de acero.",
    description:
      "Una joven costurera diagnosticada con polio bulbar paralítica logra respirar por sí misma tras seis meses en un pulmón de acero. Su caso fue documentado como un 'milagro de la ciencia' en la prensa local, inspirando campañas de vacunación barriales.",
    location: "Antiguo Hospital Juárez, Cuauhtémoc, CDMX",
    coords: { lat: 19.4251, lng: -99.1293 },
    tags: ["salud", "polio", "esperanza", "medicina"],
  },
  {
    id: "e32",
    title: "Renuncia del relojero mayor de Catedral",
    type: "JOB_RESIGNATION",
    intensity: "3",
    date: "1913-02-01",
    excerpt: "El relojero de Catedral renunció en plena Decena Trágica por daño auditivo.",
    description:
      "El encargado de dar mantenimiento a los relojes de la Catedral Metropolitana renuncia irrevocablemente durante la Decena Trágica, argumentando que el sonido de los cañonazos había arruinado su oído absoluto, indispensable para afinar las campanas.",
    location: "Catedral Metropolitana, Cuauhtémoc, CDMX",
    coords: { lat: 19.4333, lng: -99.1332 },
    tags: ["oficios", "revolución", "sonido", "decisiones"],
  },
  {
    id: "e33",
    title: "Desalojo de la vecindad El Fénix",
    type: "RELOCATION",
    intensity: "4",
    date: "1978-10-12",
    excerpt: "Decenas de familias fueron desalojadas en la Guerrero por obras viales.",
    description:
      "Más de 40 familias son forzadas a abandonar una vecindad centenaria en la colonia Guerrero para dar paso a la ampliación del Eje Central. Las pertenencias de los inquilinos quedaron en la calle bajo una lluvia torrencial.",
    location: "Trazo del Eje Central, Colonia Guerrero, Cuauhtémoc, CDMX",
    coords: { lat: 19.4412, lng: -99.1415 },
    tags: ["urbanismo", "desalojo", "tristeza", "modernidad"],
  },
  {
    id: "e34",
    title: "Plantón de novio en la Parroquia de la Profesa",
    type: "RELATIONSHIP_END",
    intensity: "5",
    date: "1955-06-18",
    excerpt: "Una boda de alta sociedad terminó con fuga del novio y escándalo público.",
    description:
      "Una heredera de una fábrica de jabones es abandonada en el altar frente a 300 invitados. El novio huyó en un tranvía hacia Xochimilco tras dejar una nota confesando que amaba a la hermana menor de la novia.",
    location: "Templo de La Profesa, Calle Madero, Cuauhtémoc, CDMX",
    coords: { lat: 19.4331, lng: -99.1368 },
    tags: ["amor", "traición", "sociedad", "cotilleo"],
  },
  {
    id: "e35",
    title: "Despido de telefonista por escuchar secretos",
    type: "JOB_TERMINATION",
    intensity: "2",
    date: "1928-03-04",
    excerpt: "Una operadora fue despedida por intervenir una llamada privada.",
    description:
      "La compañía de teléfonos despide a una joven operadora del centro de conexiones de la colonia Juárez. Fue sorprendida interrumpiendo una llamada para corregir a un caballero que le mentía a su esposa sobre su paradero.",
    location: "Central Telefónica de Victoria, Cuauhtémoc, CDMX",
    coords: { lat: 19.4298, lng: -99.1444 },
    tags: ["trabajo", "chisme", "tecnología", "cotidiano"],
  },
  {
    id: "e36",
    title: "Voto de silencio de un oficinista",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "1981-09-07",
    excerpt: "Un contador en Tlatelolco decidió no volver a hablar y comunicarse por escrito.",
    description:
      "Un contador de una dependencia gubernamental en Tlatelolco, harto de la burocracia, toma un voto de silencio absoluto. Renunció a hablar y se comunicó solo con notas escritas durante los siguientes 12 años, sin abandonar su vida civil.",
    location: "Torre Insignia, Tlatelolco, Cuauhtémoc, CDMX",
    coords: { lat: 19.4502, lng: -99.1396 },
    tags: ["excentricidad", "burocracia", "aislamiento", "decisiones"],
  },
  {
    id: "e37",
    title: "Descarrilamiento de tranvía en Tlalpan",
    type: "ACCIDENT",
    intensity: "3",
    date: "1907-08-12",
    excerpt: "Un tranvía se descarriló en la ruta a Tlalpan tras invadir la vía un animal.",
    description:
      "Un tranvía eléctrico que viajaba del Zócalo a San Agustín de las Cuevas (Tlalpan) se descarrila por una vaca en las vías cerca de Churubusco. Los pasajeros resultaron ilesos, pero pasaron la noche cantando a la intemperie.",
    location: "Calzada de Tlalpan a la altura de Churubusco, Coyoacán, CDMX",
    coords: { lat: 19.3551, lng: -99.1415 },
    tags: ["transporte", "tranvías", "accidente leve", "anecdotario"],
  },
  {
    id: "e38",
    title: "Fundación del asilo de animales La Esperanza",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1932-11-15",
    excerpt: "Una vecina de la Roma abrió un refugio informal para perros y gatos callejeros.",
    description:
      "Una viuda de la colonia Roma convierte el patio trasero de su casona de la calle de Colima en el primer refugio informal para perros y gatos callejeros, enfrentando quejas de sanidad pero salvando a cientos de animales.",
    location: "Calle de Colima, Colonia Roma, Cuauhtémoc, CDMX",
    coords: { lat: 19.4192, lng: -99.1601 },
    tags: ["animales", "altruismo", "vida cotidiana", "esperanza"],
  },
  {
    id: "e39",
    title: "Juicio por el loro grosero de la Merced",
    type: "LEGAL_EVENT",
    intensity: "2",
    date: "1958-10-01",
    excerpt: "Una disputa comercial llegó a tribunales por insultos repetidos por un loro.",
    description:
      "Una extraña querella civil: un carnicero del mercado de la Merced demanda a la dueña de un puesto de frutas porque su loro de compañía gritaba insultos sobre la frescura de su carne frente a la clientela.",
    location: "Mercado de la Merced, Venustiano Carranza, CDMX",
    coords: { lat: 19.4255, lng: -99.1245 },
    tags: ["humor", "leyes", "mercados", "cotidiano"],
  },
  {
    id: "e40",
    title: "Muerte de un carpintero por astilla infectada",
    type: "DEATH",
    intensity: "3",
    date: "1919-04-21",
    excerpt: "Un maestro ebanista falleció por septicemia tras una herida laboral no tratada.",
    description:
      "Un ebanista maestro de la colonia Santa María la Ribera, reconocido por tallar muebles para la aristocracia porfiriana en decadencia, fallece trágicamente de gangrena provocada por una astilla de caoba no tratada.",
    location: "Santa María la Ribera, Cuauhtémoc, CDMX",
    coords: { lat: 19.4485, lng: -99.1578 },
    tags: ["oficios", "tragedia", "salud", "carpintería"],
  },
  {
    id: "e41",
    title: "Vendedora de lotería regala su propio billete ganador",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "1966-12-24",
    excerpt: "Una vendedora regaló un billete que resultó premio mayor en Nochebuena.",
    description:
      "En un acto de generosidad incomprensible, una vendedora ambulante en el Paseo de la Reforma regala el cachito de lotería que no pudo vender a un organillero ciego. El billete resultó ser el premio mayor de Nochebuena.",
    location: "Glorieta de la Palma, Reforma, Cuauhtémoc, CDMX",
    coords: { lat: 19.4284, lng: -99.1643 },
    tags: ["altruismo", "lotería", "milagro urbano", "decisiones"],
  },
  {
    id: "e42",
    title: "Diagnóstico y aislamiento por tuberculosis de un poeta",
    type: "HEALTH_DIAGNOSIS",
    intensity: "3",
    date: "1941-01-01",
    excerpt: "Un poeta fue aislado en Huipulco tras diagnóstico de tuberculosis pulmonar.",
    description:
      "Un joven poeta es diagnosticado con tuberculosis pulmonar y forzado a abandonar sus estudios y tertulias en el Centro Histórico para recluirse en el Sanatorio para Tuberculosos de Huipulco, en el sur de la ciudad, donde escribiría su mejor obra.",
    location: "Sanatorio de Huipulco (hoy INER), Tlalpan, CDMX",
    coords: { lat: 19.2905, lng: -99.1557 },
    tags: ["salud", "literatura", "aislamiento", "melancolía"],
  },
  {
    id: "e43",
    title: "Ruptura del dueto Los Jilgueros del Sur",
    type: "RELATIONSHIP_END",
    intensity: "2",
    date: "1970-11-02",
    excerpt: "Un dueto vernáculo se separó en vivo en medio de acusaciones personales.",
    description:
      "En pleno escenario del Teatro Blanquita, un famoso dueto de música vernácula se separa irremediablemente. Durante la presentación, uno de ellos acusó al otro al micrófono de haberle robado los arreglos de guitarra y a su esposa.",
    location: "Teatro Blanquita, Cuauhtémoc, CDMX",
    coords: { lat: 19.4402, lng: -99.1411 },
    tags: ["espectáculos", "traición", "música popular", "ruptura"],
  },
  {
    id: "e44",
    title: "Clausura de la Pulquería Los Hombres Sin Miedo",
    type: "LEGAL_EVENT",
    intensity: "3",
    date: "1951-05-05",
    excerpt: "Salubridad cerró una pulquería emblemática de Peralvillo por prácticas insalubres.",
    description:
      "Inspectores de salubridad clausuran definitivamente una mítica pulquería en la colonia Peralvillo tras encontrar que usaban ingredientes no regulados ('muñecas' de trapo misteriosas) para fermentar la bebida, desatando protestas de los parroquianos.",
    location: "Colonia Peralvillo, Cuauhtémoc, CDMX",
    coords: { lat: 19.4582, lng: -99.1352 },
    tags: ["pulque", "salubridad", "clausura", "cultura popular"],
  },
  {
    id: "e45",
    title: "La mudanza de los elefantes del zoológico",
    type: "RELOCATION",
    intensity: "3",
    date: "1980-07-01",
    excerpt: "Una caravana nocturna trasladó elefantes de Chapultepec a Aragón.",
    description:
      "Ante la remodelación del zoológico de Chapultepec, un grupo de elefantes es trasladado temporalmente a San Juan de Aragón en una lenta caravana de camiones plataforma durante la madrugada. Vecinos de Insurgentes salieron en pijama a verlos pasar.",
    location: "Ruta de Chapultepec a San Juan de Aragón, CDMX",
    coords: { lat: 19.4619, lng: -99.0833 },
    tags: ["animales", "ciudad", "surrealismo", "mudanza"],
  },
  {
    id: "e46",
    title: "Renuncia de la actriz de radioteatro en vivo",
    type: "JOB_RESIGNATION",
    intensity: "3",
    date: "1948-10-12",
    excerpt: "Una actriz renunció al aire durante una transmisión en vivo en la XEW.",
    description:
      "La protagonista estrella de la radionovela 'El Derecho de Llorar' renuncia en plena transmisión en vivo desde los estudios de la XEW, afirmando llorando al micrófono que los guiones demeritaban la inteligencia de la mujer mexicana.",
    location: "Estudios de la XEW, Ayuntamiento 52, Cuauhtémoc, CDMX",
    coords: { lat: 19.4305, lng: -99.1458 },
    tags: ["radio", "dignidad", "feminismo", "espectáculos"],
  },
  {
    id: "e47",
    title: "Despido del dibujante de mapas del catastro",
    type: "JOB_TERMINATION",
    intensity: "2",
    date: "1960-06-01",
    excerpt: "Un cartógrafo fue cesado por alterar planos oficiales con elementos ficticios.",
    description:
      "Un cartógrafo del Departamento del Distrito Federal es despedido tras descubrirse que llevaba años dibujando calles imaginarias y pequeños monstruos marinos en los planos oficiales de las nuevas colonias periféricas del oriente.",
    location: "Oficinas del DDF, Zócalo, Cuauhtémoc, CDMX",
    coords: { lat: 19.4326, lng: -99.1332 },
    tags: ["cartografía", "burocracia", "arte oculto", "rebeldía"],
  },
  {
    id: "e48",
    title: "Sobreviviente del derrumbe del multifamiliar Juárez",
    type: "HEALTH_DIAGNOSIS",
    intensity: "5",
    date: "1985-09-23",
    excerpt: "Rescatistas extrajeron con vida a un bebé tras cuatro días entre escombros.",
    description:
      "Cuatro días después del sismo del 85, rescatistas extraen de los escombros del multifamiliar Juárez a un bebé recién nacido milagrosamente ileso. El diagnóstico médico confirma deshidratación pero salud estable, convirtiéndose en el símbolo de la esperanza nacional.",
    location: "Multifamiliar Juárez, Colonia Roma Sur, Cuauhtémoc, CDMX",
    coords: { lat: 19.4102, lng: -99.1558 },
    tags: ["sismo", "rescate", "milagro", "supervivencia"],
  },
  {
    id: "e49",
    title: "Apertura de la primera tienda de discos de importación",
    type: "NEW_BEGINNING",
    intensity: "2",
    date: "1958-04-01",
    excerpt: "En Zona Rosa abrió una tienda pionera de vinilos importados.",
    description:
      "Dos jóvenes abren 'Hi-Fi Discos' en un pequeño local de la Zona Rosa, la primera tienda dedicada exclusivamente a importar vinilos de jazz, blues y el incipiente rock n' roll, convirtiéndose en refugio de la juventud rebelde de la ciudad.",
    location: "Calle de Génova, Zona Rosa, Cuauhtémoc, CDMX",
    coords: { lat: 19.4265, lng: -99.1631 },
    tags: ["música", "vinilos", "juventud", "zona rosa"],
  },
  {
    id: "e50",
    title: "Hombre dona su herencia a la Cruz Roja",
    type: "MAJOR_DECISION",
    intensity: "3",
    date: "1993-01-09",
    excerpt: "Un ex-ferrocarrilero legó su patrimonio completo a la Cruz Roja Mexicana.",
    description:
      "Un solitario ex-ferrocarrilero fallece y se revela en su testamento que dejó su casa completa en Azcapotzalco, llena de herramientas y ahorros en monedas de plata, a la Cruz Roja Mexicana, desheredando a sus sobrinos lejanos.",
    location: "Barrio de San Miguel, Azcapotzalco, CDMX",
    coords: { lat: 19.4812, lng: -99.1865 },
    tags: ["testamento", "altruismo", "dinero", "decisiones"],
  },
]
