import type { ObservationEvent } from "@/types/event"

/** Metro Line 2 historical events. */
export const METRO_EVENTS: ObservationEvent[] = [
  {
    id: "me01",
    title: "Inauguración de la expansión terminal Cuatro Caminos",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1984-08-22",
    excerpt: "La estación Cuatro Caminos fue inaugurada como la nueva terminal norponiente de la Línea 2.",
    description:
      "La estación Cuatro Caminos fue inaugurada como la nueva terminal norponiente de la Línea 2. La decisión arquitectónica y logística de crear este nodo terminal transformó radicalmente la movilidad de cientos de miles de trabajadores diarios.",
    location: "Metro Cuatro Caminos, Naucalpan",
    coords: { lat: 19.45959, lng: -99.21584 },
    tags: ["metro", "línea 2", "inauguración"],
  },
  {
    id: "me02",
    title: "Demolición del histórico Toreo de Cuatro Caminos",
    type: "RELOCATION",
    intensity: "3",
    date: "2008-01-01",
    excerpt: "El emblemático Toreo de Cuatro Caminos fue clausurado y demolido de manera definitiva.",
    description:
      "El emblemático Toreo de Cuatro Caminos, la colosal plaza de toros y centro de espectáculos que dio su identidad histórica y su iconografía a la estación del metro, fue clausurado y posteriormente demolido de manera definitiva.",
    location: "Metro Cuatro Caminos, Lomas de Sotelo",
    coords: { lat: 19.45959, lng: -99.21584 },
    tags: ["metro", "demolición", "toreo"],
  },
  {
    id: "me03",
    title: "Modernización integral del CETRAM Cuatro Caminos",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "2014-01-01",
    excerpt: "Se aprobó y ejecutó una remodelación integral del Centro de Transferencia Modal.",
    description:
      "Se aprobó y ejecutó una remodelación integral del Centro de Transferencia Modal (CETRAM) norte y sur de Cuatro Caminos, transformando uno de los paraderos de autobuses más caóticos de América Latina en un complejo terminal cerrado y modernizado.",
    location: "Metro Cuatro Caminos, Naucalpan",
    coords: { lat: 19.45959, lng: -99.21584 },
    tags: ["metro", "cetram", "remodelación"],
  },
  {
    id: "me04",
    title: "Inauguración de la estación Metro Panteones",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1984-08-22",
    excerpt: "La estación Panteones fue inaugurada como parte de la expansión norponiente de la Línea 2.",
    description:
      "La estación Panteones fue inaugurada como parte de la última expansión norponiente de la Línea 2 del Metro, estableciendo una conexión subterránea vital entre la histórica zona de Tacuba y la frontera con el Estado de México.",
    location: "Metro Panteones, Miguel Hidalgo",
    coords: { lat: 19.45864, lng: -99.20295 },
    tags: ["metro", "panteones", "inauguración"],
  },
  {
    id: "me05",
    title: "Ejecución de túneles profundos bajo zonas funerarias",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "1982-01-01",
    excerpt: "Se aplicaron técnicas avanzadas de excavación en la zona entre Tacuba y Panteones.",
    description:
      "Durante la planificación y ejecución del túnel profundo que conecta las estaciones Tacuba y Panteones, los ingenieros del STC tomaron la decisión crítica de aplicar técnicas avanzadas de excavación debido a los complejos desafíos geológicos.",
    location: "Metro Panteones, Argentina Antigua",
    coords: { lat: 19.45864, lng: -99.20295 },
    tags: ["metro", "ingeniería", "túneles"],
  },
  {
    id: "me06",
    title: "Surgimiento del mito urbano de los fantasmas de Panteones",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1990-01-01",
    excerpt: "Reportes de anomalías auditivas y visuales en los túneles hacia Tacuba.",
    description:
      "Operadores de trenes de servicio nocturno, trabajadores de mantenimiento y usuarios comenzaron a reportar sistemáticamente anomalías auditivas y visuales en los oscuros túneles que se extienden hacia Tacuba.",
    location: "Metro Panteones, Miguel Hidalgo",
    coords: { lat: 19.45864, lng: -99.20295 },
    tags: ["metro", "mito urbano", "leyendas"],
  },
  {
    id: "me07",
    title: "Inauguración de la estación original Metro Tacuba",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1970-09-14",
    excerpt: "Tacuba fue inaugurada como la terminal norte original de la Línea 2.",
    description:
      "La estación Tacuba fue inaugurada oficialmente como la terminal norte original de la Línea 2 del Metro, consolidando un hito fundacional en la historia del STC.",
    location: "Metro Tacuba, Tacuba",
    coords: { lat: 19.45938, lng: -99.18823 },
    tags: ["metro", "tacuba", "inauguración"],
  },
  {
    id: "me08",
    title: "Apertura del transbordo monumental con la Línea 7",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1984-12-20",
    excerpt: "Se inauguraron los pasillos de correspondencia entre la Línea 2 y la Línea 7.",
    description:
      "Se inauguraron los inmensos pasillos de correspondencia y túneles de transferencia que conectan la Línea 2 con la recién construida Línea 7 del STC Metro, transformando a Tacuba en uno de los nodos de transbordo más profundos del sistema.",
    location: "Metro Tacuba, Miguel Hidalgo",
    coords: { lat: 19.45938, lng: -99.18823 },
    tags: ["metro", "transbordo", "línea 7"],
  },
  {
    id: "me09",
    title: "Consolidación de la leyenda de las risas en el transbordo",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "2000-01-01",
    excerpt: "La leyenda de las risas de niños invisibles en el corredor de transbordo.",
    description:
      "El extenso pasillo de transbordo entre la Línea 2 y la Línea 7 en Tacuba se consolidó como el epicentro de uno de los fenómenos de folklore urbano más arraigados: la leyenda de las risas perdidas.",
    location: "Metro Tacuba, Tacuba",
    coords: { lat: 19.45938, lng: -99.18823 },
    tags: ["metro", "leyenda", "folklore"],
  },
  {
    id: "me10",
    title: "Inauguración de la estación Metro Cuitláhuac",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-09-14",
    excerpt: "Cuitláhuac inaugurada rindiendo homenaje al penúltimo tlatoani mexica.",
    description:
      "La estación Cuitláhuac fue inaugurada rindiendo homenaje, mediante su nombre e iconografía, al penúltimo tlatoani mexica, famoso por haber liderado la expulsión victoriosa de las tropas españolas durante la Noche Triste.",
    location: "Metro Cuitláhuac, Popotla",
    coords: { lat: 19.45725, lng: -99.1815 },
    tags: ["metro", "cuitláhuac", "historia"],
  },
  {
    id: "me11",
    title: "Reforzamiento geotécnico profundo de la estación",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "1969-01-01",
    excerpt: "Implementación de soluciones de cimentación profunda en Cuitláhuac.",
    description:
      "Durante los trabajos previos a la inauguración de Cuitláhuac, los ingenieros enfrentaron problemas severos de hundimientos diferenciales. Se implementaron soluciones de cimentación profunda y bombeo electrosmótico.",
    location: "Metro Cuitláhuac, Miguel Hidalgo",
    coords: { lat: 19.45725, lng: -99.1815 },
    tags: ["metro", "ingeniería", "geotecnia"],
  },
  {
    id: "me12",
    title: "Articulación cultural de la Fiesta de la Identidad",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "2017-05-28",
    excerpt: "La estación como punto focal de la Fiesta de la Identidad cultural.",
    description:
      "La memoria histórica vinculada a la figura de Cuitláhuac generó resonancias culturales. La estación funcionó como punto focal simbólico para el lanzamiento de la Fiesta de la Identidad.",
    location: "Metro Cuitláhuac, Popotla",
    coords: { lat: 19.45725, lng: -99.1815 },
    tags: ["metro", "cultura", "identidad"],
  },
  {
    id: "me13",
    title: "Inauguración de la estación Metro Popotla",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-09-14",
    excerpt: "Popotla inaugurada en uno de los puntos más cargados de historia de la Calzada México-Tacuba.",
    description:
      "Se inauguró la estación Popotla, insertándose estratégicamente en uno de los puntos más cargados de historia. Su logotipo presenta el icónico árbol ahuehuete bajo el cual Hernán Cortés supuestamente lloró su derrota en 1520.",
    location: "Metro Popotla, Popotla",
    coords: { lat: 19.45291, lng: -99.17549 },
    tags: ["metro", "popotla", "náhuatl"],
  },
  {
    id: "me14",
    title: "Incendio intencional del Árbol de la Noche Triste",
    type: "ACCIDENT",
    intensity: "5",
    date: "1980-01-10",
    excerpt: "El ahuehuete histórico de Popotla sufrió un devastador ataque intencional.",
    description:
      "El vetusto ahuehuete histórico, situado a pocos pasos de la salida de la estación Popotla, sufrió un devastador ataque intencional cuando individuos no identificados le prendieron fuego.",
    location: "Metro Popotla, Miguel Hidalgo",
    coords: { lat: 19.45291, lng: -99.17549 },
    tags: ["metro", "árbol", "vandalismo"],
  },
  {
    id: "me15",
    title: "Renombramiento decolonial a la Plaza de la Noche Victoriosa",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "2021-07-27",
    excerpt: "El espacio fue rebautizado de Árbol de la Noche Triste a Noche Victoriosa.",
    description:
      "En una decisión de política decolonial, se alteró oficialmente la nomenclatura. El espacio conocido como Plaza del Árbol de la Noche Triste fue rebautizado como Plaza de la Noche Victoriosa.",
    location: "Metro Popotla, Popotla",
    coords: { lat: 19.45291, lng: -99.17549 },
    tags: ["metro", "decolonial", "memoria"],
  },
  {
    id: "me16",
    title: "Inauguración de la estación Metro Colegio Militar",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-09-14",
    excerpt: "Colegio Militar inició operaciones brindando servicio al norponiente.",
    description:
      "La estación Colegio Militar inició operaciones brindando servicio a un enclave crítico del norponiente, cerca de las antiguas instalaciones de la academia castrense nacional.",
    location: "Metro Colegio Militar, Un Hogar para Nosotros",
    coords: { lat: 19.44927, lng: -99.17178 },
    tags: ["metro", "colegio militar", "inauguración"],
  },
  {
    id: "me17",
    title: "Inauguración de la exposición y murales del Ejército Mexicano",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "2018-03-23",
    excerpt: "Exposición fotográfica y murales en los muros de Colegio Militar.",
    description:
      "Se inauguró una vasta exposición fotográfica y serie de intervenciones visuales murales en los muros principales de la estación Colegio Militar, relatan la evolución y actividades del Ejército Mexicano.",
    location: "Metro Colegio Militar, Miguel Hidalgo",
    coords: { lat: 19.44927, lng: -99.17178 },
    tags: ["metro", "exposición", "ejército"],
  },
  {
    id: "me18",
    title: "Aprobación de la iconografía castrense en el STC",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "1969-05-01",
    excerpt: "Lance Wyman adoptó elementos heráldicos para la iconografía de Colegio Militar.",
    description:
      "Durante la fase de planeación de identidad gráfica dirigida por Lance Wyman, se aprobó el uso del escudo del Heroico Colegio Militar para la iconografía de la estación.",
    location: "Metro Colegio Militar, Miguel Hidalgo",
    coords: { lat: 19.44927, lng: -99.17178 },
    tags: ["metro", "diseño", "wyman"],
  },
  {
    id: "me19",
    title: "Inauguración de la estación Metro Normal",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-09-14",
    excerpt: "Normal inaugurada cerca de la Benemérita Escuela Nacional de Maestros.",
    description:
      "Se inauguró formalmente la estación Metro Normal, denominada así por su cercanía a la Benemérita Escuela Nacional de Maestros, concebida como el nodo principal de movilidad para el sector magisterial.",
    location: "Metro Normal, Tlaxpana",
    coords: { lat: 19.44456, lng: -99.16727 },
    tags: ["metro", "normal", "educación"],
  },
  {
    id: "me20",
    title: "Masacre estudiantil del Halconazo en las afueras de la estación",
    type: "DEATH",
    intensity: "5",
    date: "1971-06-10",
    excerpt: "La Masacre del Jueves de Corpus ocurrió en las inmediaciones de Metro Normal.",
    description:
      "En las inmediaciones de la estación Metro Normal se desató una de las tragedias políticas más oscuras: la Masacre del Jueves de Corpus (El Halconazo). Una marcha pacífica de estudiantes fue emboscada brutalmente por Los Halcones.",
    location: "Metro Normal, Miguel Hidalgo",
    coords: { lat: 19.44456, lng: -99.16727 },
    tags: ["metro", "halconazo", "represión"],
  },
  {
    id: "me21",
    title: "Consolidación de la estación como punto cero de exigencia de justicia",
    type: "LEGAL_EVENT",
    intensity: "4",
    date: "2006-06-10",
    excerpt: "La explanada de Normal se consolidó como epicentro de marchas conmemorativas.",
    description:
      "La estación Normal se consolidó como el epicentro de las marchas anuales del 10 de junio que exigen el esclarecimiento histórico y castigo a los autores intelectuales de la represión de 1971.",
    location: "Metro Normal, Tlaxpana",
    coords: { lat: 19.44456, lng: -99.16727 },
    tags: ["metro", "memoria", "justicia"],
  },
  {
    id: "me22",
    title: "Inauguración de la estación Metro San Cosme",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-09-14",
    excerpt: "San Cosme inaugurada en el corazón de la histórica Ribera de San Cosme.",
    description:
      "La estación San Cosme fue inaugurada exitosamente, ubicándose en el corazón de la histórica Ribera de San Cosme, una de las zonas comerciales más tradicionales de la capital.",
    location: "Metro San Cosme, San Rafael",
    coords: { lat: 19.4419, lng: -99.16066 },
    tags: ["metro", "san cosme", "inauguración"],
  },
  {
    id: "me23",
    title: "Colapsos estructurales aledaños por el sismo de 1985",
    type: "ACCIDENT",
    intensity: "5",
    date: "1985-09-19",
    excerpt: "El área de San Cosme sufrió devastaciones inmensas por el terremoto.",
    description:
      "El fatídico terremoto de 8.0 grados sacudió la zona. El área circundante a San Cosme sufrió devastaciones inmensas, con el colapso de edificios históricos y vecindades a lo largo de la Ribera.",
    location: "Metro San Cosme, Cuauhtémoc",
    coords: { lat: 19.4419, lng: -99.16066 },
    tags: ["metro", "sismo 85", "tragedia"],
  },
  {
    id: "me24",
    title: "Integración del colector profundo San Cosme",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "1995-01-01",
    excerpt: "Se construyó el colector profundo Guillermo Prieto bajo la estación.",
    description:
      "Para mitigar los problemas de hundimiento e inundaciones, el gobierno tomó la decisión de integrar una masiva obra de drenaje bajo la estación, el colector profundo Guillermo Prieto.",
    location: "Metro San Cosme, Cuauhtémoc",
    coords: { lat: 19.4419, lng: -99.16066 },
    tags: ["metro", "drenaje", "ingeniería"],
  },
  {
    id: "me25",
    title: "Inauguración de la estación Metro Revolución",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1970-09-14",
    excerpt: "Revolución comenzó operaciones cerca del Monumento a la Revolución.",
    description:
      "La estación Revolución comenzó operaciones como parte integral de la primera fase de la Línea 2, destacando por su cercanía monumental con el imponente Monumento a la Revolución Mexicana.",
    location: "Metro Revolución, Tabacalera",
    coords: { lat: 19.43923, lng: -99.15423 },
    tags: ["metro", "revolución", "monumento"],
  },
  {
    id: "me26",
    title: "Asignación como centro logístico de los desfiles del 20 de Noviembre",
    type: "MAJOR_DECISION",
    intensity: "3",
    date: "1970-11-20",
    excerpt: "Revolución consolidada como punto de concentración para desfiles cívicos.",
    description:
      "Las autoridades consolidaron a la estación como el principal punto de concentración y organización logística para los masivos desfiles que celebran anualmente el aniversario de la Revolución Mexicana.",
    location: "Metro Revolución, Cuauhtémoc",
    coords: { lat: 19.43923, lng: -99.15423 },
    tags: ["metro", "desfiles", "ceremonial"],
  },
  {
    id: "me27",
    title: "Remodelación arquitectónica en sincronía con la Plaza de la República",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "2014-01-01",
    excerpt: "Proyecto de remodelación e iluminación de la estación Revolución.",
    description:
      "Se aprobó un extenso proyecto de remodelación arquitectónica e iluminación de los interiores y exteriores de la estación Revolución, alineando su estética con la revitalización de la Plaza de la República.",
    location: "Metro Revolución, Tabacalera",
    coords: { lat: 19.43923, lng: -99.15423 },
    tags: ["metro", "remodelación", "plaza"],
  },
  {
    id: "me28",
    title: "Inauguración de la estación Metro Hidalgo",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1970-09-14",
    excerpt: "Hidalgo inaugurada en la encrucijada del centro histórico y Reforma.",
    description:
      "La estación Hidalgo fue formalmente inaugurada, ubicándose estratégicamente en la encrucijada del centro histórico colonial y el Paseo de la Reforma, justo a las espaldas de la Alameda Central.",
    location: "Metro Hidalgo, Centro",
    coords: { lat: 19.43755, lng: -99.14722 },
    tags: ["metro", "hidalgo", "centro"],
  },
  {
    id: "me29",
    title: "Apertura del mega-transbordo con la Línea 3",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-11-20",
    excerpt: "Se inauguraron los túneles de transferencia entre Línea 2 y Línea 3.",
    description:
      "Se inauguraron los túneles y pasillos de transferencia que conectan la Línea 2 con la recién terminada Línea 3, transformando a Hidalgo en una mega-estación de correspondencia.",
    location: "Metro Hidalgo, Cuauhtémoc",
    coords: { lat: 19.43755, lng: -99.14722 },
    tags: ["metro", "transbordo", "línea 3"],
  },
  {
    id: "me30",
    title: "Surgimiento del culto masivo a San Judas Tadeo en el templo contiguo",
    type: "NEW_BEGINNING",
    intensity: "5",
    date: "1982-10-28",
    excerpt: "Las congregaciones mensuales de devotos de San Judas inundaron la estación.",
    description:
      "Inició un fenómeno sociorreligioso masivo: las congregaciones mensuales de los devotos de San Judas Tadeo. Cada día 28, la estación Hidalgo se ve literalmente inundada por decenas de miles de feligreses.",
    location: "Metro Hidalgo, Guerrero",
    coords: { lat: 19.43755, lng: -99.14722 },
    tags: ["metro", "san judas", "culto"],
  },
  {
    id: "me31",
    title: "Inauguración de la estación Metro Bellas Artes",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1970-09-14",
    excerpt: "Bellas Artes abierta bajo la avenida Hidalgo, frente al Palacio.",
    description:
      "La estación Bellas Artes fue abierta al público, destacándose por su localización bajo la avenida Hidalgo, colindando de frente con el majestuoso Palacio de Bellas Artes y la Alameda Central.",
    location: "Metro Bellas Artes, Centro",
    coords: { lat: 19.43638, lng: -99.14161 },
    tags: ["metro", "bellas artes", "cultura"],
  },
  {
    id: "me32",
    title: "Instalación del acceso estilo Guimard donado por el Metro de París",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1998-11-14",
    excerpt: "Se instaló un edículo Art Nouveau donado por el Métro de París.",
    description:
      "Se inauguró un edículo de diseño Art Nouveau (estilo Guimard) original, donado por la RATP del Métro de París a la Ciudad de México, a cambio de una obra huichol instalada en París.",
    location: "Metro Bellas Artes, Centro Histórico",
    coords: { lat: 19.43638, lng: -99.14161 },
    tags: ["metro", "guimard", "parís"],
  },
  {
    id: "me33",
    title: "Cumbre de Arqueología del INAH por el 50 aniversario del Metro",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "2019-09-05",
    excerpt: "Exposición sobre hallazgos arqueológicos bajo la red del STC.",
    description:
      "El Palacio de Bellas Artes fue sede de la exposición 'El Metro y la arqueología de la Ciudad de México', conmemorando el 50 aniversario de las operaciones de salvamento del INAH bajo la red del STC.",
    location: "Metro Bellas Artes, Centro Histórico",
    coords: { lat: 19.43638, lng: -99.14161 },
    tags: ["metro", "arqueología", "inah"],
  },
  {
    id: "me34",
    title: "Inauguración de la estación Metro Allende",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-09-14",
    excerpt: "Allende inaugurada sobre la emblemática calle de Tacuba.",
    description:
      "La estación Allende fue inaugurada como un punto de acceso vital situado sobre la emblemática calle de Tacuba, uno de los cuatro ejes viales originales trazados por los mexicas.",
    location: "Metro Allende, Centro Histórico",
    coords: { lat: 19.43556, lng: -99.13687 },
    tags: ["metro", "allende", "centro"],
  },
  {
    id: "me35",
    title: "Apertura del Museo de la Tortura junto a la estación",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "2012-01-01",
    excerpt: "Abrió el Museo de la Tortura sobre la calle de Tacuba.",
    description:
      "A pocos metros de la salida de Allende abrió el controversial Museo de la Tortura, exhibiendo instrumentos de tortura europeos y virreinales de la época de la Inquisición.",
    location: "Metro Allende, Cuauhtémoc",
    coords: { lat: 19.43556, lng: -99.13687 },
    tags: ["metro", "museo", "tortura"],
  },
  {
    id: "me36",
    title: "Clausura indefinida de la estación por la pandemia de COVID-19",
    type: "HEALTH_DIAGNOSIS",
    intensity: "5",
    date: "2020-12-08",
    excerpt: "Allende fue cerrada temporalmente durante el pico de contagios COVID-19.",
    description:
      "En el pico de contagios por COVID-19, las autoridades ordenaron el cierre temporal de la estación Allende junto con Zócalo para desincentivar la afluencia al Centro Histórico.",
    location: "Metro Allende, Centro Histórico",
    coords: { lat: 19.43556, lng: -99.13687 },
    tags: ["metro", "covid", "clausura"],
  },
  {
    id: "me37",
    title: "Inauguración de la estación Metro Zócalo bajo la Plaza de la Constitución",
    type: "NEW_BEGINNING",
    intensity: "5",
    date: "1970-09-14",
    excerpt: "Zócalo inaugurada exactamente bajo la principal plaza pública del país.",
    description:
      "La estación Zócalo se inauguró ubicándose exactamente bajo la principal plaza pública del país. La obra implicó excavar con extrema delicadeza para no comprometer los cimientos de la Catedral y el Palacio Nacional.",
    location: "Metro Zócalo/Tenochtitlan, Centro Histórico",
    coords: { lat: 19.4325, lng: -99.13225 },
    tags: ["metro", "zócalo", "tenochtitlan"],
  },
  {
    id: "me38",
    title: "Decreto de cambio de nombre a Zócalo/Tenochtitlan",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "2021-07-14",
    excerpt: "La estación fue rebautizada Zócalo/Tenochtitlan por reivindicación decolonial.",
    description:
      "El Gobierno de la CDMX emitió un decreto para modificar la nomenclatura de la estación, cambiando su nombre de Zócalo a Zócalo/Tenochtitlan en el marco de los 500 años de la caída del imperio mexica.",
    location: "Metro Zócalo/Tenochtitlan, Cuauhtémoc",
    coords: { lat: 19.4325, lng: -99.13225 },
    tags: ["metro", "decolonial", "tenochtitlan"],
  },
  {
    id: "me39",
    title: "Cancelación de la estación Salvador y origen del Pasaje Zócalo",
    type: "MAJOR_DECISION",
    intensity: "3",
    date: "1969-01-01",
    excerpt: "La galería excavada se transformó en el Pasaje Zócalo-Pino Suárez.",
    description:
      "La cancelación de una estación intermedia proyectada llevó a transformar ingeniosamente el hueco excavado en un colosal corredor subterráneo que dio origen al Pasaje Zócalo-Pino Suárez.",
    location: "Metro Zócalo/Tenochtitlan, Centro Histórico",
    coords: { lat: 19.4325, lng: -99.13225 },
    tags: ["metro", "pasaje", "libros"],
  },
  {
    id: "me40",
    title: "Inauguración de la estación y nodo de transferencia Pino Suárez",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1970-08-01",
    excerpt: "Pino Suárez inaugurada como punto de transferencia seminal del STC.",
    description:
      "La estación Pino Suárez fue inaugurada como el punto de transferencia seminal del STC, conectando por primera vez la Línea 1 con el tramo de la Línea 2 hacia el sur.",
    location: "Metro Pino Suárez, Centro",
    coords: { lat: 19.42438, lng: -99.13294 },
    tags: ["metro", "pino suárez", "transbordo"],
  },
  {
    id: "me41",
    title: "Magno hallazgo y preservación del Adoratorio a Ehécatl",
    type: "NEW_BEGINNING",
    intensity: "5",
    date: "1968-01-01",
    excerpt: "Las excavaciones descubrieron la pirámide circular del dios del viento.",
    description:
      "Durante las excavaciones para el túnel de correspondencia en Pino Suárez, las palas chocaron contra una masiva estructura de piedra. Los arqueólogos del INAH develaron el Adoratorio del Dios Ehécatl, una pirámide circular mexica.",
    location: "Metro Pino Suárez, Centro Histórico",
    coords: { lat: 19.42438, lng: -99.13294 },
    tags: ["metro", "ehécatl", "arqueología"],
  },
  {
    id: "me42",
    title: "Clausura y asedio estructural por el terremoto de 1985",
    type: "ACCIDENT",
    intensity: "5",
    date: "1985-09-19",
    excerpt: "Varios edificios colapsaron sobre los accesos de Pino Suárez.",
    description:
      "El terremoto de 1985 impactó brutalmente. Varios complejos de edificios colapsaron sobre la superficie, sellando los accesos de la estación. Las autoridades clausuraron la estación por un período prolongado.",
    location: "Metro Pino Suárez, Cuauhtémoc",
    coords: { lat: 19.42438, lng: -99.13294 },
    tags: ["metro", "sismo 85", "tragedia"],
  },
  {
    id: "me43",
    title: "Inauguración de la estación superficial San Antonio Abad",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "San Antonio Abad marca donde la Línea 2 emerge del túnel a la superficie.",
    description:
      "Se inauguró la estación San Antonio Abad, el punto donde la Línea 2 abandona el túnel subterráneo y emerge majestuosamente hacia la superficie sobre la Calzada de Tlalpan.",
    location: "Metro San Antonio Abad, Obrera",
    coords: { lat: 19.41602, lng: -99.13454 },
    tags: ["metro", "san antonio abad", "superficie"],
  },
  {
    id: "me44",
    title: "Tragedia por el colapso de las fábricas de costureras",
    type: "DEATH",
    intensity: "5",
    date: "1985-09-19",
    excerpt: "Unas 600 costureras murieron en fábricas colapsadas cerca de San Antonio Abad.",
    description:
      "Durante el terremoto de 1985, múltiples fábricas textiles colapsaron a pocos metros de la estación. Aproximadamente 600 trabajadoras perdieron la vida. Las montañas de escombros obstaculizaron temporalmente el tránsito.",
    location: "Metro San Antonio Abad, Tránsito",
    coords: { lat: 19.41602, lng: -99.13454 },
    tags: ["metro", "sismo 85", "costureras"],
  },
  {
    id: "me45",
    title: "Fundación del Sindicato de Costureras 19 de Septiembre",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "1985-10-18",
    excerpt: "Las sobrevivientes fundaron el Sindicato 19 de Septiembre.",
    description:
      "De entre las ruinas, un movimiento obrero liderado por las sobrevivientes del desastre textil tomó la decisión histórica de fundar el Sindicato Nacional de Trabajadores de la Industria de la Costura 19 de Septiembre.",
    location: "Metro San Antonio Abad, Obrera",
    coords: { lat: 19.41602, lng: -99.13454 },
    tags: ["metro", "sindicato", "costureras"],
  },
  {
    id: "me46",
    title: "Inauguración de la estación superficial Chabacano",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "Chabacano inaugurada con la Solución Barcelona de andenes.",
    description:
      "La estación Chabacano fue inaugurada con la disposición de plataformas mediante la Solución Barcelona: un andén central para descenso y dos andenes laterales para abordaje.",
    location: "Metro Chabacano, Vista Alegre",
    coords: { lat: 19.40918, lng: -99.13562 },
    tags: ["metro", "chabacano", "ingeniería"],
  },
  {
    id: "me47",
    title: "La fatídica salida del tren No. 8 desde el andén",
    type: "ACCIDENT",
    intensity: "5",
    date: "1975-10-20",
    excerpt: "El tren 8 aceleró sin frenos y chocó contra otro convoy en Chabacano.",
    description:
      "El tren número 8 cerró sus puertas e inició su recorrido fatal desde Chabacano. Por razones que se debatirían ampliamente, el conductor interpretó erróneamente las señales. El tren aceleró sin aplicar los frenos.",
    location: "Metro Chabacano, Cuauhtémoc",
    coords: { lat: 19.40918, lng: -99.13562 },
    tags: ["metro", "accidente", "choque"],
  },
  {
    id: "me48",
    title: "Conclusión del mega-nodo de transbordo de tres líneas",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "1994-07-20",
    excerpt: "Chabacano se convirtió en centro de transferencia de tres líneas.",
    description:
      "Se completaron las obras que interconectaron las líneas 8 y 9 con la Línea 2 en Chabacano, convirtiéndola en un mega-centro de transferencia de tres niveles.",
    location: "Metro Chabacano, Vista Alegre",
    coords: { lat: 19.40918, lng: -99.13562 },
    tags: ["metro", "transbordo", "mega-nodo"],
  },
  {
    id: "me49",
    title: "Inauguración de la estación puente Metro Viaducto",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "Viaducto inaugurada sobre la intersección del Viaducto y Tlalpan.",
    description:
      "La estación Viaducto fue inaugurada sobre la intersección del Viaducto Río de la Piedad y la Calzada de Tlalpan, integrando el sistema mediante pilares y puentes peatonales.",
    location: "Metro Viaducto, Álamos",
    coords: { lat: 19.40087, lng: -99.1369 },
    tags: ["metro", "viaducto", "puente"],
  },
  {
    id: "me50",
    title: "El histórico y mortífero choque de trenes en Viaducto",
    type: "DEATH",
    intensity: "5",
    date: "1975-10-20",
    excerpt: "El tren 8 se estrelló contra el convoy 10, dejando 31 muertos.",
    description:
      "El tren número 8 que venía de Chabacano a unos 70 km/h se estrelló violentamente por alcance contra el convoy 10 detenido en Viaducto. El siniestro más letal de la red, con al menos 31 muertos.",
    location: "Metro Viaducto, Santa Anita",
    coords: { lat: 19.40087, lng: -99.1369 },
    tags: ["metro", "choque", "tragedia"],
  },
  {
    id: "me51",
    title: "Implementación del Piloto Automático y cajas negras en el STC",
    type: "MAJOR_DECISION",
    intensity: "4",
    date: "1976-01-01",
    excerpt: "Tras el choque de Viaducto se implementó el Piloto Automático obligatorio.",
    description:
      "Como consecuencia del choque en Viaducto, el STC tomó la decisión de erradicar los sistemas de conducción exclusivamente manuales e implementar el Piloto Automático y cajas negras en cada cabina.",
    location: "Metro Viaducto, Iztacalco",
    coords: { lat: 19.40087, lng: -99.1369 },
    tags: ["metro", "seguridad", "piloto automático"],
  },
  {
    id: "me52",
    title: "Inauguración de la estación Metro Xola y su iconografía",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "Xola inaugurada con el logotipo de la palmera datilera de Lance Wyman.",
    description:
      "Se inauguró la estación Xola. Lance Wyman seleccionó el dibujo de una palmera datilera como logotipo, inmortalizando el gigantesco árbol que dominaba el paisaje aledaño.",
    location: "Metro Xola, Álamos",
    coords: { lat: 19.39521, lng: -99.13781 },
    tags: ["metro", "xola", "wyman"],
  },
  {
    id: "me53",
    title: "Plantación de la icónica palmera monumental de Xola",
    type: "NEW_BEGINNING",
    intensity: "2",
    date: "1920-01-01",
    excerpt: "El dueño de una casona plantó una palmera traída de Guadalajara.",
    description:
      "El dueño de una casona en los terrenos de la futura Xola tomó la decisión de trasladar desde Guadalajara y plantar una majestuosa palmera datilera en su jardín.",
    location: "Metro Xola, Benito Juárez",
    coords: { lat: 19.39521, lng: -99.13781 },
    tags: ["metro", "palmera", "historia"],
  },
  {
    id: "me54",
    title: "Tala por enfermedad del árbol histórico de la estación",
    type: "DEATH",
    intensity: "4",
    date: "2022-04-24",
    excerpt: "La centenaria palmera de Xola fue talada por plaga de hongos.",
    description:
      "Tras más de cien años, la legendaria palmera de Xola enfermó mortalmente por una plaga de hongos. Las autoridades emitieron el veredicto de tala por riesgo de colapso sobre los carriles.",
    location: "Metro Xola, Moderna",
    coords: { lat: 19.39521, lng: -99.13781 },
    tags: ["metro", "palmera", "tala"],
  },
  {
    id: "me55",
    title: "Inauguración de la estación Metro Villa de Cortés",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "Villa de Cortés puesta en funcionamiento en el tramo sur superficial.",
    description:
      "La estación Villa de Cortés fue puesta en funcionamiento. Su diseño se distinguió por estar incrustada en un nivel elevado sobre los puentes vehiculares.",
    location: "Metro Villa de Cortés, Villa de Cortés",
    coords: { lat: 19.38758, lng: -99.13896 },
    tags: ["metro", "villa de cortés", "inauguración"],
  },
  {
    id: "me56",
    title: "Adopción de iconografía alusiva al encuentro de dos mundos",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "1969-01-01",
    excerpt: "Se eligió el yelmo conquistador para la iconografía de Villa de Cortés.",
    description:
      "Los planificadores tomaron la decisión de emplear el dibujo de un yelmo de soldado conquistador español para la iconografía de la estación, homenajeando a Hernán Cortés y el encuentro con Moctezuma.",
    location: "Metro Villa de Cortés, Benito Juárez",
    coords: { lat: 19.38758, lng: -99.13896 },
    tags: ["metro", "iconografía", "conquista"],
  },
  {
    id: "me57",
    title: "Accidente fatal en zona de obras bajo el puente de la estación",
    type: "ACCIDENT",
    intensity: "4",
    date: "2019-09-13",
    excerpt: "Un automóvil colisionó contra los macizos de obras bajo Villa de Cortés.",
    description:
      "Durante obras de remodelación, un automóvil que circulaba a exceso de velocidad colisionó catastróficamente contra los macizos de protección bajo los andenes. Dos personas fallecieron.",
    location: "Metro Villa de Cortés, Benito Juárez",
    coords: { lat: 19.38758, lng: -99.13896 },
    tags: ["metro", "accidente", "obras"],
  },
  {
    id: "me58",
    title: "Inauguración de la gran terminal multimodal Metro Tasqueña",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1970-08-01",
    excerpt: "Tasqueña abrió como terminal sur de la Línea 2.",
    description:
      "La estación terminal Tasqueña abrió sus puertas, finalizando el gran trazo sur original de la Línea 2. La terminal se proyectó como la principal compuerta multimodal de entrada y salida para millones de personas del sur.",
    location: "Metro Tasqueña, Campestre Churubusco",
    coords: { lat: 19.34376, lng: -99.13953 },
    tags: ["metro", "tasqueña", "terminal"],
  },
  {
    id: "me59",
    title: "El histórico primer descarrilamiento de trenes en la red del STC",
    type: "ACCIDENT",
    intensity: "4",
    date: "1972-01-01",
    excerpt: "Primer gran accidente mecánico documentado en Tasqueña.",
    description:
      "La estación Tasqueña tiene el honor de haber sido escenario del primer gran accidente mecánico documentado del STC. Un convoy perdió adherencia y sufrió un violento descarrilamiento en las vías de maniobra.",
    location: "Metro Tasqueña, Coyoacán",
    coords: { lat: 19.34376, lng: -99.13953 },
    tags: ["metro", "descarrilamiento", "accidente"],
  },
  {
    id: "me60",
    title: "Interconexión y consolidación de la central del Tren Ligero",
    type: "MAJOR_DECISION",
    intensity: "3",
    date: "1986-08-01",
    excerpt: "Se inauguró el sistema del Tren Ligero anclado a Tasqueña.",
    description:
      "El gobierno inauguró el sistema del Tren Ligero eléctrico directamente a los andenes de Tasqueña, elevándola al estatus de Mega-Hub Metropolitano hacia Tlalpan y Xochimilco.",
    location: "Metro Tasqueña, Campestre Churubusco",
    coords: { lat: 19.34376, lng: -99.13953 },
    tags: ["metro", "tren ligero", "xochimilco"],
  },
  {
    id: "me61",
    title: "Inauguración de la estación Metro Nativitas",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "Nativitas inaugurada en referencia al templo de Santa María de la Natividad.",
    description:
      "Se inauguró la estación Nativitas, nombrada en referencia al antiguo templo parroquial y a la herencia lacustre que caracterizó a esta franja del Valle de México.",
    location: "Metro Nativitas, Nativitas",
    coords: { lat: 19.37953, lng: -99.14019 },
    tags: ["metro", "nativitas", "inauguración"],
  },
  {
    id: "me62",
    title: "Desmantelamiento y demolición de la Hacienda del Lago",
    type: "RELOCATION",
    intensity: "3",
    date: "1965-01-01",
    excerpt: "La Hacienda del Lago fue demolida antes de la construcción del metro.",
    description:
      "La legendaria Hacienda del Lago sufrió una fase de deterioro y posterior demolición. Los terrenos fueron adquiridos para centros comerciales y las rutas del STC Metro.",
    location: "Metro Nativitas, Benito Juárez",
    coords: { lat: 19.37953, lng: -99.14019 },
    tags: ["metro", "hacienda", "demolición"],
  },
  {
    id: "me63",
    title: "Fundación del Centro Cultural Nativitas",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "2003-09-03",
    excerpt: "Se inauguró el Centro Cultural Nativitas para la promoción de las artes.",
    description:
      "Las autoridades tomaron posesión de una casa-habitación y la inauguraron como el Centro Cultural Nativitas, preservando la vitalidad artística del barrio frente a la gentrificación.",
    location: "Metro Nativitas, Nativitas",
    coords: { lat: 19.37953, lng: -99.14019 },
    tags: ["metro", "cultura", "centro cultural"],
  },
  {
    id: "me64",
    title: "Inauguración de la estación comercial Metro Portales",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "Portales inaugurada para servir a una de las colonias más dinámicas del sur.",
    description:
      "La estación Portales fue inaugurada para dotar de transporte rápido a una de las colonias más efervescentes y tradicionalmente populares del sur de la Ciudad de México.",
    location: "Metro Portales, Portales Norte",
    coords: { lat: 19.36992, lng: -99.14157 },
    tags: ["metro", "portales", "comercio"],
  },
  {
    id: "me65",
    title: "Erradicación y traslado de las fábricas ladrilleras históricas",
    type: "RELOCATION",
    intensity: "3",
    date: "1950-01-01",
    excerpt: "Las ladrilleras dominaban el área antes del metro.",
    description:
      "El área que hoy envuelve a Portales estaba dominada por inmensas industrias de manufactura de tabique. La expansión urbana empujó a estas fábricas hacia las periferias del Estado de México.",
    location: "Metro Portales, Portales Sur",
    coords: { lat: 19.36992, lng: -99.14157 },
    tags: ["metro", "ladrilleras", "industria"],
  },
  {
    id: "me66",
    title: "Consolidación del legendario Mercado de Portales",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "1957-01-01",
    excerpt: "Se inauguró el Mercado de Portales y su tianguis de pulgas.",
    description:
      "Años antes de la excavación de la estación, se inauguró el legendario Mercado de Portales. Cuando el Metro comenzó a operar, ambos se alimentaron mutuamente forjando un ecosistema comercial indisoluble.",
    location: "Metro Portales, Benito Juárez",
    coords: { lat: 19.36992, lng: -99.14157 },
    tags: ["metro", "mercado", "tianguis"],
  },
  {
    id: "me67",
    title: "Inauguración de la estación Metro Ermita",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "Ermita inaugurada en la intersección del Eje 8 Sur y Calzada de Tlalpan.",
    description:
      "Se inauguró la estación Ermita, ubicada en la intersección del Eje 8 Sur y la Calzada de Tlalpan. Su nomenclatura recoge la figura de una ermita colonial que daba posada a los viajeros.",
    location: "Metro Ermita, Ermita",
    coords: { lat: 19.36198, lng: -99.1429 },
    tags: ["metro", "ermita", "inauguración"],
  },
  {
    id: "me68",
    title: "Colapso masivo de losa de techo sobre tren de pasajeros",
    type: "ACCIDENT",
    intensity: "4",
    date: "1986-01-01",
    excerpt: "Una losa de concreto se desplomó sobre un vagón en Ermita.",
    description:
      "Una pesada losa de concreto del techo de la estación Ermita se desprendió e impactó contra el techo de un vagón que arribaba. Afortunadamente no se reportaron víctimas fatales.",
    location: "Metro Ermita, Benito Juárez",
    coords: { lat: 19.36198, lng: -99.1429 },
    tags: ["metro", "accidente", "colapso"],
  },
  {
    id: "me69",
    title: "Choque aparatoso de convoyes por omisión de protocolo",
    type: "ACCIDENT",
    intensity: "4",
    date: "1995-06-05",
    excerpt: "Dos trenes chocaron en Ermita por desactivación del Piloto Automático.",
    description:
      "Dos trenes chocaron violentamente en Ermita. Las indagatorias revelaron que un operador desactivó el Piloto Automático y manejó en modo manual libre, suprimiendo las distancias de seguridad.",
    location: "Metro Ermita, Miravalle",
    coords: { lat: 19.36198, lng: -99.1429 },
    tags: ["metro", "choque", "negligencia"],
  },
  {
    id: "me70",
    title: "Inauguración de la estación Metro General Anaya",
    type: "NEW_BEGINNING",
    intensity: "3",
    date: "1970-08-01",
    excerpt: "General Anaya inaugurada como penúltima parada del trazo sur.",
    description:
      "La estación General Anaya fue inaugurada como la penúltima parada del trazo de la Línea Azul al sur, ubicada en los bordes de Coyoacán.",
    location: "Metro General Anaya, Churubusco",
    coords: { lat: 19.35324, lng: -99.14501 },
    tags: ["metro", "general anaya", "churubusco"],
  },
  {
    id: "me71",
    title: "Adjudicación como homenaje cívico al héroe de Churubusco",
    type: "MAJOR_DECISION",
    intensity: "2",
    date: "1969-01-01",
    excerpt: "La estación fue dedicada al General Pedro María Anaya.",
    description:
      "La Comisión de Nomenclatura del STC emitió el fallo para dedicar el nombre al General Pedro María Anaya, héroe de la resistencia durante la invasión estadounidense de 1847 en Churubusco.",
    location: "Metro General Anaya, Coyoacán",
    coords: { lat: 19.35324, lng: -99.14501 },
    tags: ["metro", "anaya", "historia"],
  },
  {
    id: "me72",
    title: "Consolidación como acceso de convenciones masivas y el Anime Fest",
    type: "NEW_BEGINNING",
    intensity: "4",
    date: "2023-10-28",
    excerpt: "El Centro Churubusco es sede de Anime Fest y convenciones masivas.",
    description:
      "El Centro de Convenciones Churubusco se transformó en sede masiva de convenciones juveniles. Eventos como el Anime Fest congregan a más de 8,000 asistentes que saturan los andenes del Metro General Anaya.",
    location: "Metro General Anaya, Churubusco",
    coords: { lat: 19.35324, lng: -99.14501 },
    tags: ["metro", "anime fest", "convenciones"],
  },
]
