-- Seed events from lib/data.ts and lib/metro-events.ts
-- Generated by scripts/generate-seed-sql.cjs

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1567, 19.4194), 4326)::geography,
  '2021-03-14T12:00:00Z'::timestamptz,
  'Había una claridad extraña en el aire, como si el tiempo hubiera decidido detenerse justo antes de que yo lo notara. No hubo señal. Solo el momento antes y el momento después, irreversiblemente distintos.',
  'La última vez que dormí sin recordar',
  'Ciudad de México, Colonia Roma',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-96.7234, 17.0669), 4326)::geography,
  '2019-08-22T12:00:00Z'::timestamptz,
  'No era la grieta lo que me perturbaba, sino lo que imaginaba al otro lado. Una apertura que no debería existir, un testimonio mudo de que las cosas se rompen sin pedir permiso.',
  'El grieta en la pared del cuarto viejo',
  'Oaxaca, Centro Histórico',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELATIONSHIP_END'::event_type,
  ST_SetSRID(ST_MakePoint(-58.3703, -34.6218), 4326)::geography,
  '2022-11-05T12:00:00Z'::timestamptz,
  'Alguien dijo algo que resonó con algo dicho meses antes por alguien completamente diferente. El hilo invisible entre ambas frases se tensó, vibró, y se cortó cuando quise atraparlo.',
  'El hilo que conectaba dos conversaciones',
  'Buenos Aires, San Telmo',
  '1'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-3.7009, 40.4084), 4326)::geography,
  '2020-06-30T12:00:00Z'::timestamptz,
  'Estaba ahí, esperando. Yo también. Ninguno cedió. Esa puerta sigue ahí en algún lugar de mi cartografía interior, siempre entreabierta, siempre sin cruzar.',
  'La puerta que no volví a abrir',
  'Madrid, Lavapiés',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-103.3117, 20.6337), 4326)::geography,
  '2023-02-01T12:00:00Z'::timestamptz,
  'No había corriente de aire. Simplemente se fue. Quedamos a oscuras los tres, y nadie habló por un tiempo que se sintió más largo de lo que fue.',
  'Cuando la vela se apagó sola',
  'Guadalajara, Tlaquepaque',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(135.7681, 35.0116), 4326)::geography,
  '2018-05-17T12:00:00Z'::timestamptz,
  'Kintsugi, decían. Pero a veces las roturas simplemente son roturas, sin metáfora redentora. Esta taza se rompió y ya no existe de la misma forma. Eso es todo.',
  'La fractura en la cerámica',
  'Kyoto',
  '1'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELATIONSHIP_END'::event_type,
  ST_SetSRID(ST_MakePoint(-9.1327, 38.7147), 4326)::geography,
  '2024-01-18T12:00:00Z'::timestamptz,
  'Tres veces el mismo número en tres días distintos. No creo en señales, pero las anoto. El hilo rojo entre ellas lo tejí yo, lo sé, pero tejido ya, no se puede destejer.',
  'El hilo rojo de las coincidencias',
  'Lisboa, Alfama',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELOCATION'::event_type,
  ST_SetSRID(ST_MakePoint(-56.1913, -34.9058), 4326)::geography,
  '2017-09-09T12:00:00Z'::timestamptz,
  'Demolieron el edificio. La puerta debe estar en algún vertedero, convertida en astillas. Pero en mi mapa sigue estando ahí, en sus coordenadas originales, esperando una mano.',
  'La puerta de la casa que ya no existe',
  'Montevideo, Ciudad Vieja',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-6.0022, 37.3812), 4326)::geography,
  '2015-12-20T12:00:00Z'::timestamptz,
  'Se enciende siempre la misma llama, aunque cambie quien la sostenga. He visto encender velas por personas muy distintas, y siempre es el mismo gesto, el mismo silencio al bajar la cerilla.',
  'La vela de todos los velatorios',
  'Sevilla, Triana',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-65.0381, -42.7692), 4326)::geography,
  '2022-07-07T12:00:00Z'::timestamptz,
  'Un momento en que el presente se rompió y pude ver simultáneamente lo que había sido y lo que sería. Duró apenas un segundo. Pero ese segundo tiene coordenadas propias en mi mapa.',
  'Grieta en el tiempo',
  'Patagonia',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELATIONSHIP_END'::event_type,
  ST_SetSRID(ST_MakePoint(-96.1332, 19.1771), 4326)::geography,
  '2024-08-03T12:00:00Z'::timestamptz,
  'Un olor. Solo un olor, el de la lluvia sobre tierra caliente. Y de repente tenía ocho años, estaba en el patio de casa, y el hilo que une ese niño con quien soy ahora se tensó con una claridad que casi dolió.',
  'El hilo que ata la infancia a este momento',
  'Veracruz',
  '1'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1413, 19.4353), 4326)::geography,
  '2023-09-15T12:00:00Z'::timestamptz,
  'Estaba en el vestíbulo del Palacio de Bellas Artes, mirando hacia el techo antes de entrar a la función. En ese momento supe que cruzar o no cruzar esa puerta cambiaría algo. No sabía qué. Entré.',
  'En el vestíbulo de Bellas Artes',
  'Ciudad de México, Centro Histórico, cerca de Bellas Artes',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-75.4794, 10.391), 4326)::geography,
  '2023-06-21T12:00:00Z'::timestamptz,
  'Alguien la dejó así, entreabierta, a las cinco y media de la mañana. No sé si fue un descuido o una invitación. Me quedé mirando la franja de luz sin entrar. Hay umbrales que se respetan.',
  'La puerta entreabierta al amanecer',
  'Cartagena de Indias',
  '1'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1678, 19.4215), 4326)::geography,
  '1941-04-01T12:00:00Z'::timestamptz,
  'Se destapa la macabra red de tráfico de menores operada por Felícitas Sánchez Neyra. La policía encontró cráneos y restos de bebés calcinados o arrojados al drenaje en su pensión de la colonia Roma.',
  'Descubrimiento de La Ogresa de la Roma',
  'Salamanca 9, Colonia Roma, Cuauhtémoc, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1861, 19.4583), 4326)::geography,
  '1942-09-01T12:00:00Z'::timestamptz,
  'Captura de Gregorio Cárdenas Hernández, un brillante estudiante de química que estranguló a cuatro mujeres, incluyendo a su novia, enterrándolas en el jardín de su casa en Tacuba. Se convirtió en un fenómeno mediático.',
  'Arresto de El Estrangulador de Tacuba',
  'Calle Mar del Norte, Tacuba, Miguel Hidalgo, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1492, 19.4217), 4326)::geography,
  '1945-01-01T12:00:00Z'::timestamptz,
  'El arquitecto Francisco Saldaña Galván, acorralado por las deudas y la presión de construir un monumental y esotérico hotel-manicomio que fusionaba masonería y arte gótico, se ahorca en el campanario de su obra inacabada.',
  'Suicidio en la Posada del Sol',
  'La Posada del Sol, Niños Héroes 139, Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'LEGAL_EVENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1533, 19.4355), 4326)::geography,
  '1901-11-17T12:00:00Z'::timestamptz,
  'Redada policial secreta en una mansión de la colonia Tabacalera donde se celebraba un baile de hombres de la alta sociedad, la mitad vestidos de mujer. Se rumora que el participante 42, yerno de Porfirio Díaz, fue encubierto.',
  'El Baile de los 41',
  'Calle de la Paz (hoy Ezequiel Montes), Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'LEGAL_EVENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1863, 19.426), 4326)::geography,
  '1985-12-25T12:00:00Z'::timestamptz,
  'Aprovechando la falta de vigilancia en Navidad, dos estudiantes de veterinaria saltan la barda del museo y saquean 140 piezas invaluables, incluyendo la máscara de jade del Dios Murciélago.',
  'El robo del siglo en el Museo de Antropología',
  'Museo Nacional de Antropología, Miguel Hidalgo, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELOCATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1883, 19.3752), 4326)::geography,
  '1968-06-29T12:00:00Z'::timestamptz,
  'Demolición y cierre definitivo del Manicomio General ''La Castañeda''. Los miles de pacientes, hacinados y maltratados durante décadas, fueron trasladados a granjas psiquiátricas modernas bajo un operativo cuasi militar.',
  'Operación Castañeda (Cierre del manicomio)',
  'Manicomio La Castañeda, Mixcoac, Álvaro Obregón, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1415, 19.4442), 4326)::geography,
  '2007-10-08T12:00:00Z'::timestamptz,
  'La policía irrumpe en el departamento de José Luis Calva Zepeda, un poeta y novelista frustrado de estética oscura. Hallaron a su pareja descuartizada en un clóset y carne humana guisándose con limón en la estufa.',
  'Arresto del Caníbal de la Guerrero',
  'Mosqueta 198, Colonia Guerrero, Cuauhtémoc, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1245, 19.4459), 4326)::geography,
  '2001-10-31T12:00:00Z'::timestamptz,
  'Enriqueta Romero (Doña Queta) saca una estatua de tamaño real de la Santa Muerte a la acera de su casa en Tepito. Se convierte en el primer santuario callejero de este culto subterráneo, congregando a miles de marginados.',
  'Primer altar público a la Santa Muerte',
  'Alfarería 12, Tepito, Cuauhtémoc, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1332, 19.4287), 4326)::geography,
  '1946-11-24T12:00:00Z'::timestamptz,
  'Tras más de un siglo de permanecer escondidos en un muro para evitar la furia popular, un grupo de historiadores desentierra en secreto los restos de Cortés en el Hospital de Jesús para autenticarlos y devolverlos al nicho.',
  'Descubrimiento de los huesos de Hernán Cortés',
  'Iglesia de Jesús Nazareno, Cuauhtémoc, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1866, 19.3444), 4326)::geography,
  '1928-07-17T12:00:00Z'::timestamptz,
  'El presidente electo Obregón es asesinado durante un banquete en el restaurante La Bombilla por José de León Toral, un fanático cristero que fingió ser dibujante de caricaturas para acercarse a su mesa y dispararle a quemarropa.',
  'Asesinato del Gral. Álvaro Obregón en La Bombilla',
  'Parque de la Bombilla, Álvaro Obregón, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1357, 19.4009), 4326)::geography,
  '1975-10-20T12:00:00Z'::timestamptz,
  'El accidente más fatal en la historia del STC Metro (antes de la Línea 12). Un tren alcanzó a otro estacionado en Viaducto a casi 70 km/h debido a una supuesta falla en el pilotaje automático, dejando más de 30 muertos.',
  'Choque de trenes del Metro Viaducto',
  'Estación Metro Viaducto (Línea 2), Iztacalco, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1676, 19.427), 4326)::geography,
  '1957-07-28T12:00:00Z'::timestamptz,
  'Un terremoto de magnitud 7.9 sacude la ciudad en la madrugada, provocando la aparatosa caída de la estatua de la Victoria Alada desde la cima del Monumento a la Independencia. La cabeza rodó por el pavimento.',
  'El sismo que derribó al Ángel',
  'Paseo de la Reforma, Colonia Juárez, Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1578, 19.4352), 4326)::geography,
  '2000-10-20T12:00:00Z'::timestamptz,
  'El antro caribeño más grande y ostentoso de la ciudad, tapizado de materiales inflamables ilegales, arde de madrugada. Las salidas de emergencia estaban cerradas con candado. Murieron 22 personas calcinadas o asfixiadas.',
  'Incendio del Lobohombo',
  'Insurgentes Norte 32 (Av. Antonio Caso), Cuauhtémoc, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1098, 19.4682), 4326)::geography,
  '1978-01-01T12:00:00Z'::timestamptz,
  'Durante las excavaciones profundas para la construcción de la Línea 4, los ingenieros desentierran los restos fosilizados de un mamut del Pleistoceno, evidenciando la megafauna que habitaba el lago primigenio.',
  'Aparición de los monolitos en Metro Talismán',
  'Estación Metro Talismán, Gustavo A. Madero, CDMX',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1491, 19.4357), 4326)::geography,
  '1927-11-23T12:00:00Z'::timestamptz,
  'El sacerdote jesuita Miguel Agustín Pro es fusilado sin juicio previo por órdenes del presidente Plutarco Elías Calles, acusado falsamente de atentar contra Álvaro Obregón. Murió con los brazos en cruz gritando ''¡Viva Cristo Rey!''.',
  'Fusilamiento del Padre Pro',
  'Comandancia de Policía (Lotería Nacional actual), Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'LEGAL_EVENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.0986, 19.4308), 4326)::geography,
  '2006-01-25T12:00:00Z'::timestamptz,
  'Juana Barraza fue detenida en la alcaldía Iztapalapa tras ser sorprendida huyendo de la escena de un homicidio. Se le atribuyeron múltiples asesinatos de mujeres adultas mayores cometidos entre 1998 y 2006. El caso generó pánico social y fuertes críticas a la investigación inicial, que perfilaba erróneamente al agresor como hombre.',
  'Captura de Juana Barraza, La Mataviejitas',
  'Colonia Moctezuma Segunda Sección, Venustiano Carranza, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.187, 19.4595), 4326)::geography,
  '1942-01-01T12:00:00Z'::timestamptz,
  'Gregorio ''Goyo'' Cárdenas, estudiante de química, confesó y fue vinculado con el asesinato de varias mujeres cuyos cuerpos fueron hallados enterrados en el patio de su domicilio en Tacuba. El caso conmocionó a la opinión pública y fue ampliamente cubierto por la prensa como ejemplo de doble vida y desviación psicológica.',
  'Descubrimiento de los cuerpos enterrados por Gregorio Cárdenas en Tacuba',
  'Tacuba, Miguel Hidalgo, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.062, 19.3569), 4326)::geography,
  '1980-01-01T12:00:00Z'::timestamptz,
  'Durante la década de 1980 circuló en colonias del oriente de la Ciudad de México el rumor de una vendedora de tamales que utilizaba carne humana en sus productos. No existen registros judiciales que confirmen el hecho, pero la historia se difundió en medios sensacionalistas y generó desconfianza y alarma entre vecinos.',
  'Leyenda urbana de la Tamalera de la muerte',
  'Zona oriente, Iztapalapa, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'HEALTH_DIAGNOSIS'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1293, 19.4251), 4326)::geography,
  '1952-05-14T12:00:00Z'::timestamptz,
  'Una joven costurera diagnosticada con polio bulbar paralítica logra respirar por sí misma tras seis meses en un pulmón de acero. Su caso fue documentado como un ''milagro de la ciencia'' en la prensa local, inspirando campañas de vacunación barriales.',
  'Milagro médico en el Hospital Juárez',
  'Antiguo Hospital Juárez, Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'JOB_RESIGNATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1332, 19.4333), 4326)::geography,
  '1913-02-01T12:00:00Z'::timestamptz,
  'El encargado de dar mantenimiento a los relojes de la Catedral Metropolitana renuncia irrevocablemente durante la Decena Trágica, argumentando que el sonido de los cañonazos había arruinado su oído absoluto, indispensable para afinar las campanas.',
  'Renuncia del relojero mayor de Catedral',
  'Catedral Metropolitana, Cuauhtémoc, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELOCATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1415, 19.4412), 4326)::geography,
  '1978-10-12T12:00:00Z'::timestamptz,
  'Más de 40 familias son forzadas a abandonar una vecindad centenaria en la colonia Guerrero para dar paso a la ampliación del Eje Central. Las pertenencias de los inquilinos quedaron en la calle bajo una lluvia torrencial.',
  'Desalojo de la vecindad El Fénix',
  'Trazo del Eje Central, Colonia Guerrero, Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELATIONSHIP_END'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1368, 19.4331), 4326)::geography,
  '1955-06-18T12:00:00Z'::timestamptz,
  'Una heredera de una fábrica de jabones es abandonada en el altar frente a 300 invitados. El novio huyó en un tranvía hacia Xochimilco tras dejar una nota confesando que amaba a la hermana menor de la novia.',
  'Plantón de novio en la Parroquia de la Profesa',
  'Templo de La Profesa, Calle Madero, Cuauhtémoc, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'JOB_TERMINATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1444, 19.4298), 4326)::geography,
  '1928-03-04T12:00:00Z'::timestamptz,
  'La compañía de teléfonos despide a una joven operadora del centro de conexiones de la colonia Juárez. Fue sorprendida interrumpiendo una llamada para corregir a un caballero que le mentía a su esposa sobre su paradero.',
  'Despido de telefonista por escuchar secretos',
  'Central Telefónica de Victoria, Cuauhtémoc, CDMX',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1396, 19.4502), 4326)::geography,
  '1981-09-07T12:00:00Z'::timestamptz,
  'Un contador de una dependencia gubernamental en Tlatelolco, harto de la burocracia, toma un voto de silencio absoluto. Renunció a hablar y se comunicó solo con notas escritas durante los siguientes 12 años, sin abandonar su vida civil.',
  'Voto de silencio de un oficinista',
  'Torre Insignia, Tlatelolco, Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1415, 19.3551), 4326)::geography,
  '1907-08-12T12:00:00Z'::timestamptz,
  'Un tranvía eléctrico que viajaba del Zócalo a San Agustín de las Cuevas (Tlalpan) se descarrila por una vaca en las vías cerca de Churubusco. Los pasajeros resultaron ilesos, pero pasaron la noche cantando a la intemperie.',
  'Descarrilamiento de tranvía en Tlalpan',
  'Calzada de Tlalpan a la altura de Churubusco, Coyoacán, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1601, 19.4192), 4326)::geography,
  '1932-11-15T12:00:00Z'::timestamptz,
  'Una viuda de la colonia Roma convierte el patio trasero de su casona de la calle de Colima en el primer refugio informal para perros y gatos callejeros, enfrentando quejas de sanidad pero salvando a cientos de animales.',
  'Fundación del asilo de animales La Esperanza',
  'Calle de Colima, Colonia Roma, Cuauhtémoc, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'LEGAL_EVENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1245, 19.4255), 4326)::geography,
  '1958-10-01T12:00:00Z'::timestamptz,
  'Una extraña querella civil: un carnicero del mercado de la Merced demanda a la dueña de un puesto de frutas porque su loro de compañía gritaba insultos sobre la frescura de su carne frente a la clientela.',
  'Juicio por el loro grosero de la Merced',
  'Mercado de la Merced, Venustiano Carranza, CDMX',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1578, 19.4485), 4326)::geography,
  '1919-04-21T12:00:00Z'::timestamptz,
  'Un ebanista maestro de la colonia Santa María la Ribera, reconocido por tallar muebles para la aristocracia porfiriana en decadencia, fallece trágicamente de gangrena provocada por una astilla de caoba no tratada.',
  'Muerte de un carpintero por astilla infectada',
  'Santa María la Ribera, Cuauhtémoc, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1643, 19.4284), 4326)::geography,
  '1966-12-24T12:00:00Z'::timestamptz,
  'En un acto de generosidad incomprensible, una vendedora ambulante en el Paseo de la Reforma regala el cachito de lotería que no pudo vender a un organillero ciego. El billete resultó ser el premio mayor de Nochebuena.',
  'Vendedora de lotería regala su propio billete ganador',
  'Glorieta de la Palma, Reforma, Cuauhtémoc, CDMX',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'HEALTH_DIAGNOSIS'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1557, 19.2905), 4326)::geography,
  '1941-01-01T12:00:00Z'::timestamptz,
  'Un joven poeta es diagnosticado con tuberculosis pulmonar y forzado a abandonar sus estudios y tertulias en el Centro Histórico para recluirse en el Sanatorio para Tuberculosos de Huipulco, en el sur de la ciudad, donde escribiría su mejor obra.',
  'Diagnóstico y aislamiento por tuberculosis de un poeta',
  'Sanatorio de Huipulco (hoy INER), Tlalpan, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELATIONSHIP_END'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1411, 19.4402), 4326)::geography,
  '1970-11-02T12:00:00Z'::timestamptz,
  'En pleno escenario del Teatro Blanquita, un famoso dueto de música vernácula se separa irremediablemente. Durante la presentación, uno de ellos acusó al otro al micrófono de haberle robado los arreglos de guitarra y a su esposa.',
  'Ruptura del dueto Los Jilgueros del Sur',
  'Teatro Blanquita, Cuauhtémoc, CDMX',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'LEGAL_EVENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1352, 19.4582), 4326)::geography,
  '1951-05-05T12:00:00Z'::timestamptz,
  'Inspectores de salubridad clausuran definitivamente una mítica pulquería en la colonia Peralvillo tras encontrar que usaban ingredientes no regulados (''muñecas'' de trapo misteriosas) para fermentar la bebida, desatando protestas de los parroquianos.',
  'Clausura de la Pulquería Los Hombres Sin Miedo',
  'Colonia Peralvillo, Cuauhtémoc, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELOCATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.0833, 19.4619), 4326)::geography,
  '1980-07-01T12:00:00Z'::timestamptz,
  'Ante la remodelación del zoológico de Chapultepec, un grupo de elefantes es trasladado temporalmente a San Juan de Aragón en una lenta caravana de camiones plataforma durante la madrugada. Vecinos de Insurgentes salieron en pijama a verlos pasar.',
  'La mudanza de los elefantes del zoológico',
  'Ruta de Chapultepec a San Juan de Aragón, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'JOB_RESIGNATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1458, 19.4305), 4326)::geography,
  '1948-10-12T12:00:00Z'::timestamptz,
  'La protagonista estrella de la radionovela ''El Derecho de Llorar'' renuncia en plena transmisión en vivo desde los estudios de la XEW, afirmando llorando al micrófono que los guiones demeritaban la inteligencia de la mujer mexicana.',
  'Renuncia de la actriz de radioteatro en vivo',
  'Estudios de la XEW, Ayuntamiento 52, Cuauhtémoc, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'JOB_TERMINATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1332, 19.4326), 4326)::geography,
  '1960-06-01T12:00:00Z'::timestamptz,
  'Un cartógrafo del Departamento del Distrito Federal es despedido tras descubrirse que llevaba años dibujando calles imaginarias y pequeños monstruos marinos en los planos oficiales de las nuevas colonias periféricas del oriente.',
  'Despido del dibujante de mapas del catastro',
  'Oficinas del DDF, Zócalo, Cuauhtémoc, CDMX',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'HEALTH_DIAGNOSIS'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1558, 19.4102), 4326)::geography,
  '1985-09-23T12:00:00Z'::timestamptz,
  'Cuatro días después del sismo del 85, rescatistas extraen de los escombros del multifamiliar Juárez a un bebé recién nacido milagrosamente ileso. El diagnóstico médico confirma deshidratación pero salud estable, convirtiéndose en el símbolo de la esperanza nacional.',
  'Sobreviviente del derrumbe del multifamiliar Juárez',
  'Multifamiliar Juárez, Colonia Roma Sur, Cuauhtémoc, CDMX',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1631, 19.4265), 4326)::geography,
  '1958-04-01T12:00:00Z'::timestamptz,
  'Dos jóvenes abren ''Hi-Fi Discos'' en un pequeño local de la Zona Rosa, la primera tienda dedicada exclusivamente a importar vinilos de jazz, blues y el incipiente rock n'' roll, convirtiéndose en refugio de la juventud rebelde de la ciudad.',
  'Apertura de la primera tienda de discos de importación',
  'Calle de Génova, Zona Rosa, Cuauhtémoc, CDMX',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1865, 19.4812), 4326)::geography,
  '1993-01-09T12:00:00Z'::timestamptz,
  'Un solitario ex-ferrocarrilero fallece y se revela en su testamento que dejó su casa completa en Azcapotzalco, llena de herramientas y ahorros en monedas de plata, a la Cruz Roja Mexicana, desheredando a sus sobrinos lejanos.',
  'Hombre dona su herencia a la Cruz Roja',
  'Barrio de San Miguel, Azcapotzalco, CDMX',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.21584, 19.45959), 4326)::geography,
  '1984-08-22T12:00:00Z'::timestamptz,
  'La estación Cuatro Caminos fue inaugurada como la nueva terminal norponiente de la Línea 2. La decisión arquitectónica y logística de crear este nodo terminal transformó radicalmente la movilidad de cientos de miles de trabajadores diarios.',
  'Inauguración de la expansión terminal Cuatro Caminos',
  'Metro Cuatro Caminos, Naucalpan',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELOCATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.21584, 19.45959), 4326)::geography,
  '2008-01-01T12:00:00Z'::timestamptz,
  'El emblemático Toreo de Cuatro Caminos, la colosal plaza de toros y centro de espectáculos que dio su identidad histórica y su iconografía a la estación del metro, fue clausurado y posteriormente demolido de manera definitiva.',
  'Demolición del histórico Toreo de Cuatro Caminos',
  'Metro Cuatro Caminos, Lomas de Sotelo',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.21584, 19.45959), 4326)::geography,
  '2014-01-01T12:00:00Z'::timestamptz,
  'Se aprobó y ejecutó una remodelación integral del Centro de Transferencia Modal (CETRAM) norte y sur de Cuatro Caminos, transformando uno de los paraderos de autobuses más caóticos de América Latina en un complejo terminal cerrado y modernizado.',
  'Modernización integral del CETRAM Cuatro Caminos',
  'Metro Cuatro Caminos, Naucalpan',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.20295, 19.45864), 4326)::geography,
  '1984-08-22T12:00:00Z'::timestamptz,
  'La estación Panteones fue inaugurada como parte de la última expansión norponiente de la Línea 2 del Metro, estableciendo una conexión subterránea vital entre la histórica zona de Tacuba y la frontera con el Estado de México.',
  'Inauguración de la estación Metro Panteones',
  'Metro Panteones, Miguel Hidalgo',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.20295, 19.45864), 4326)::geography,
  '1982-01-01T12:00:00Z'::timestamptz,
  'Durante la planificación y ejecución del túnel profundo que conecta las estaciones Tacuba y Panteones, los ingenieros del STC tomaron la decisión crítica de aplicar técnicas avanzadas de excavación debido a los complejos desafíos geológicos.',
  'Ejecución de túneles profundos bajo zonas funerarias',
  'Metro Panteones, Argentina Antigua',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.20295, 19.45864), 4326)::geography,
  '1990-01-01T12:00:00Z'::timestamptz,
  'Operadores de trenes de servicio nocturno, trabajadores de mantenimiento y usuarios comenzaron a reportar sistemáticamente anomalías auditivas y visuales en los oscuros túneles que se extienden hacia Tacuba.',
  'Surgimiento del mito urbano de los fantasmas de Panteones',
  'Metro Panteones, Miguel Hidalgo',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.18823, 19.45938), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Tacuba fue inaugurada oficialmente como la terminal norte original de la Línea 2 del Metro, consolidando un hito fundacional en la historia del STC.',
  'Inauguración de la estación original Metro Tacuba',
  'Metro Tacuba, Tacuba',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.18823, 19.45938), 4326)::geography,
  '1984-12-20T12:00:00Z'::timestamptz,
  'Se inauguraron los inmensos pasillos de correspondencia y túneles de transferencia que conectan la Línea 2 con la recién construida Línea 7 del STC Metro, transformando a Tacuba en uno de los nodos de transbordo más profundos del sistema.',
  'Apertura del transbordo monumental con la Línea 7',
  'Metro Tacuba, Miguel Hidalgo',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.18823, 19.45938), 4326)::geography,
  '2000-01-01T12:00:00Z'::timestamptz,
  'El extenso pasillo de transbordo entre la Línea 2 y la Línea 7 en Tacuba se consolidó como el epicentro de uno de los fenómenos de folklore urbano más arraigados: la leyenda de las risas perdidas.',
  'Consolidación de la leyenda de las risas en el transbordo',
  'Metro Tacuba, Tacuba',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1815, 19.45725), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Cuitláhuac fue inaugurada rindiendo homenaje, mediante su nombre e iconografía, al penúltimo tlatoani mexica, famoso por haber liderado la expulsión victoriosa de las tropas españolas durante la Noche Triste.',
  'Inauguración de la estación Metro Cuitláhuac',
  'Metro Cuitláhuac, Popotla',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1815, 19.45725), 4326)::geography,
  '1969-01-01T12:00:00Z'::timestamptz,
  'Durante los trabajos previos a la inauguración de Cuitláhuac, los ingenieros enfrentaron problemas severos de hundimientos diferenciales. Se implementaron soluciones de cimentación profunda y bombeo electrosmótico.',
  'Reforzamiento geotécnico profundo de la estación',
  'Metro Cuitláhuac, Miguel Hidalgo',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1815, 19.45725), 4326)::geography,
  '2017-05-28T12:00:00Z'::timestamptz,
  'La memoria histórica vinculada a la figura de Cuitláhuac generó resonancias culturales. La estación funcionó como punto focal simbólico para el lanzamiento de la Fiesta de la Identidad.',
  'Articulación cultural de la Fiesta de la Identidad',
  'Metro Cuitláhuac, Popotla',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.17549, 19.45291), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'Se inauguró la estación Popotla, insertándose estratégicamente en uno de los puntos más cargados de historia. Su logotipo presenta el icónico árbol ahuehuete bajo el cual Hernán Cortés supuestamente lloró su derrota en 1520.',
  'Inauguración de la estación Metro Popotla',
  'Metro Popotla, Popotla',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.17549, 19.45291), 4326)::geography,
  '1980-01-10T12:00:00Z'::timestamptz,
  'El vetusto ahuehuete histórico, situado a pocos pasos de la salida de la estación Popotla, sufrió un devastador ataque intencional cuando individuos no identificados le prendieron fuego.',
  'Incendio intencional del Árbol de la Noche Triste',
  'Metro Popotla, Miguel Hidalgo',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.17549, 19.45291), 4326)::geography,
  '2021-07-27T12:00:00Z'::timestamptz,
  'En una decisión de política decolonial, se alteró oficialmente la nomenclatura. El espacio conocido como Plaza del Árbol de la Noche Triste fue rebautizado como Plaza de la Noche Victoriosa.',
  'Renombramiento decolonial a la Plaza de la Noche Victoriosa',
  'Metro Popotla, Popotla',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.17178, 19.44927), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Colegio Militar inició operaciones brindando servicio a un enclave crítico del norponiente, cerca de las antiguas instalaciones de la academia castrense nacional.',
  'Inauguración de la estación Metro Colegio Militar',
  'Metro Colegio Militar, Un Hogar para Nosotros',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.17178, 19.44927), 4326)::geography,
  '2018-03-23T12:00:00Z'::timestamptz,
  'Se inauguró una vasta exposición fotográfica y serie de intervenciones visuales murales en los muros principales de la estación Colegio Militar, relatan la evolución y actividades del Ejército Mexicano.',
  'Inauguración de la exposición y murales del Ejército Mexicano',
  'Metro Colegio Militar, Miguel Hidalgo',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.17178, 19.44927), 4326)::geography,
  '1969-05-01T12:00:00Z'::timestamptz,
  'Durante la fase de planeación de identidad gráfica dirigida por Lance Wyman, se aprobó el uso del escudo del Heroico Colegio Militar para la iconografía de la estación.',
  'Aprobación de la iconografía castrense en el STC',
  'Metro Colegio Militar, Miguel Hidalgo',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.16727, 19.44456), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'Se inauguró formalmente la estación Metro Normal, denominada así por su cercanía a la Benemérita Escuela Nacional de Maestros, concebida como el nodo principal de movilidad para el sector magisterial.',
  'Inauguración de la estación Metro Normal',
  'Metro Normal, Tlaxpana',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.16727, 19.44456), 4326)::geography,
  '1971-06-10T12:00:00Z'::timestamptz,
  'En las inmediaciones de la estación Metro Normal se desató una de las tragedias políticas más oscuras: la Masacre del Jueves de Corpus (El Halconazo). Una marcha pacífica de estudiantes fue emboscada brutalmente por Los Halcones.',
  'Masacre estudiantil del Halconazo en las afueras de la estación',
  'Metro Normal, Miguel Hidalgo',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'LEGAL_EVENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.16727, 19.44456), 4326)::geography,
  '2006-06-10T12:00:00Z'::timestamptz,
  'La estación Normal se consolidó como el epicentro de las marchas anuales del 10 de junio que exigen el esclarecimiento histórico y castigo a los autores intelectuales de la represión de 1971.',
  'Consolidación de la estación como punto cero de exigencia de justicia',
  'Metro Normal, Tlaxpana',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.16066, 19.4419), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación San Cosme fue inaugurada exitosamente, ubicándose en el corazón de la histórica Ribera de San Cosme, una de las zonas comerciales más tradicionales de la capital.',
  'Inauguración de la estación Metro San Cosme',
  'Metro San Cosme, San Rafael',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.16066, 19.4419), 4326)::geography,
  '1985-09-19T12:00:00Z'::timestamptz,
  'El fatídico terremoto de 8.0 grados sacudió la zona. El área circundante a San Cosme sufrió devastaciones inmensas, con el colapso de edificios históricos y vecindades a lo largo de la Ribera.',
  'Colapsos estructurales aledaños por el sismo de 1985',
  'Metro San Cosme, Cuauhtémoc',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.16066, 19.4419), 4326)::geography,
  '1995-01-01T12:00:00Z'::timestamptz,
  'Para mitigar los problemas de hundimiento e inundaciones, el gobierno tomó la decisión de integrar una masiva obra de drenaje bajo la estación, el colector profundo Guillermo Prieto.',
  'Integración del colector profundo San Cosme',
  'Metro San Cosme, Cuauhtémoc',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.15423, 19.43923), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Revolución comenzó operaciones como parte integral de la primera fase de la Línea 2, destacando por su cercanía monumental con el imponente Monumento a la Revolución Mexicana.',
  'Inauguración de la estación Metro Revolución',
  'Metro Revolución, Tabacalera',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.15423, 19.43923), 4326)::geography,
  '1970-11-20T12:00:00Z'::timestamptz,
  'Las autoridades consolidaron a la estación como el principal punto de concentración y organización logística para los masivos desfiles que celebran anualmente el aniversario de la Revolución Mexicana.',
  'Asignación como centro logístico de los desfiles del 20 de Noviembre',
  'Metro Revolución, Cuauhtémoc',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.15423, 19.43923), 4326)::geography,
  '2014-01-01T12:00:00Z'::timestamptz,
  'Se aprobó un extenso proyecto de remodelación arquitectónica e iluminación de los interiores y exteriores de la estación Revolución, alineando su estética con la revitalización de la Plaza de la República.',
  'Remodelación arquitectónica en sincronía con la Plaza de la República',
  'Metro Revolución, Tabacalera',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14722, 19.43755), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Hidalgo fue formalmente inaugurada, ubicándose estratégicamente en la encrucijada del centro histórico colonial y el Paseo de la Reforma, justo a las espaldas de la Alameda Central.',
  'Inauguración de la estación Metro Hidalgo',
  'Metro Hidalgo, Centro',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14722, 19.43755), 4326)::geography,
  '1970-11-20T12:00:00Z'::timestamptz,
  'Se inauguraron los túneles y pasillos de transferencia que conectan la Línea 2 con la recién terminada Línea 3, transformando a Hidalgo en una mega-estación de correspondencia.',
  'Apertura del mega-transbordo con la Línea 3',
  'Metro Hidalgo, Cuauhtémoc',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14722, 19.43755), 4326)::geography,
  '1982-10-28T12:00:00Z'::timestamptz,
  'Inició un fenómeno sociorreligioso masivo: las congregaciones mensuales de los devotos de San Judas Tadeo. Cada día 28, la estación Hidalgo se ve literalmente inundada por decenas de miles de feligreses.',
  'Surgimiento del culto masivo a San Judas Tadeo en el templo contiguo',
  'Metro Hidalgo, Guerrero',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14161, 19.43638), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Bellas Artes fue abierta al público, destacándose por su localización bajo la avenida Hidalgo, colindando de frente con el majestuoso Palacio de Bellas Artes y la Alameda Central.',
  'Inauguración de la estación Metro Bellas Artes',
  'Metro Bellas Artes, Centro',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14161, 19.43638), 4326)::geography,
  '1998-11-14T12:00:00Z'::timestamptz,
  'Se inauguró un edículo de diseño Art Nouveau (estilo Guimard) original, donado por la RATP del Métro de París a la Ciudad de México, a cambio de una obra huichol instalada en París.',
  'Instalación del acceso estilo Guimard donado por el Metro de París',
  'Metro Bellas Artes, Centro Histórico',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14161, 19.43638), 4326)::geography,
  '2019-09-05T12:00:00Z'::timestamptz,
  'El Palacio de Bellas Artes fue sede de la exposición ''El Metro y la arqueología de la Ciudad de México'', conmemorando el 50 aniversario de las operaciones de salvamento del INAH bajo la red del STC.',
  'Cumbre de Arqueología del INAH por el 50 aniversario del Metro',
  'Metro Bellas Artes, Centro Histórico',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13687, 19.43556), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Allende fue inaugurada como un punto de acceso vital situado sobre la emblemática calle de Tacuba, uno de los cuatro ejes viales originales trazados por los mexicas.',
  'Inauguración de la estación Metro Allende',
  'Metro Allende, Centro Histórico',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13687, 19.43556), 4326)::geography,
  '2012-01-01T12:00:00Z'::timestamptz,
  'A pocos metros de la salida de Allende abrió el controversial Museo de la Tortura, exhibiendo instrumentos de tortura europeos y virreinales de la época de la Inquisición.',
  'Apertura del Museo de la Tortura junto a la estación',
  'Metro Allende, Cuauhtémoc',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'HEALTH_DIAGNOSIS'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13687, 19.43556), 4326)::geography,
  '2020-12-08T12:00:00Z'::timestamptz,
  'En el pico de contagios por COVID-19, las autoridades ordenaron el cierre temporal de la estación Allende junto con Zócalo para desincentivar la afluencia al Centro Histórico.',
  'Clausura indefinida de la estación por la pandemia de COVID-19',
  'Metro Allende, Centro Histórico',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13225, 19.4325), 4326)::geography,
  '1970-09-14T12:00:00Z'::timestamptz,
  'La estación Zócalo se inauguró ubicándose exactamente bajo la principal plaza pública del país. La obra implicó excavar con extrema delicadeza para no comprometer los cimientos de la Catedral y el Palacio Nacional.',
  'Inauguración de la estación Metro Zócalo bajo la Plaza de la Constitución',
  'Metro Zócalo/Tenochtitlan, Centro Histórico',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13225, 19.4325), 4326)::geography,
  '2021-07-14T12:00:00Z'::timestamptz,
  'El Gobierno de la CDMX emitió un decreto para modificar la nomenclatura de la estación, cambiando su nombre de Zócalo a Zócalo/Tenochtitlan en el marco de los 500 años de la caída del imperio mexica.',
  'Decreto de cambio de nombre a Zócalo/Tenochtitlan',
  'Metro Zócalo/Tenochtitlan, Cuauhtémoc',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13225, 19.4325), 4326)::geography,
  '1969-01-01T12:00:00Z'::timestamptz,
  'La cancelación de una estación intermedia proyectada llevó a transformar ingeniosamente el hueco excavado en un colosal corredor subterráneo que dio origen al Pasaje Zócalo-Pino Suárez.',
  'Cancelación de la estación Salvador y origen del Pasaje Zócalo',
  'Metro Zócalo/Tenochtitlan, Centro Histórico',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13294, 19.42438), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'La estación Pino Suárez fue inaugurada como el punto de transferencia seminal del STC, conectando por primera vez la Línea 1 con el tramo de la Línea 2 hacia el sur.',
  'Inauguración de la estación y nodo de transferencia Pino Suárez',
  'Metro Pino Suárez, Centro',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13294, 19.42438), 4326)::geography,
  '1968-01-01T12:00:00Z'::timestamptz,
  'Durante las excavaciones para el túnel de correspondencia en Pino Suárez, las palas chocaron contra una masiva estructura de piedra. Los arqueólogos del INAH develaron el Adoratorio del Dios Ehécatl, una pirámide circular mexica.',
  'Magno hallazgo y preservación del Adoratorio a Ehécatl',
  'Metro Pino Suárez, Centro Histórico',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13294, 19.42438), 4326)::geography,
  '1985-09-19T12:00:00Z'::timestamptz,
  'El terremoto de 1985 impactó brutalmente. Varios complejos de edificios colapsaron sobre la superficie, sellando los accesos de la estación. Las autoridades clausuraron la estación por un período prolongado.',
  'Clausura y asedio estructural por el terremoto de 1985',
  'Metro Pino Suárez, Cuauhtémoc',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13454, 19.41602), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'Se inauguró la estación San Antonio Abad, el punto donde la Línea 2 abandona el túnel subterráneo y emerge majestuosamente hacia la superficie sobre la Calzada de Tlalpan.',
  'Inauguración de la estación superficial San Antonio Abad',
  'Metro San Antonio Abad, Obrera',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13454, 19.41602), 4326)::geography,
  '1985-09-19T12:00:00Z'::timestamptz,
  'Durante el terremoto de 1985, múltiples fábricas textiles colapsaron a pocos metros de la estación. Aproximadamente 600 trabajadoras perdieron la vida. Las montañas de escombros obstaculizaron temporalmente el tránsito.',
  'Tragedia por el colapso de las fábricas de costureras',
  'Metro San Antonio Abad, Tránsito',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13454, 19.41602), 4326)::geography,
  '1985-10-18T12:00:00Z'::timestamptz,
  'De entre las ruinas, un movimiento obrero liderado por las sobrevivientes del desastre textil tomó la decisión histórica de fundar el Sindicato Nacional de Trabajadores de la Industria de la Costura 19 de Septiembre.',
  'Fundación del Sindicato de Costureras 19 de Septiembre',
  'Metro San Antonio Abad, Obrera',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13562, 19.40918), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'La estación Chabacano fue inaugurada con la disposición de plataformas mediante la Solución Barcelona: un andén central para descenso y dos andenes laterales para abordaje.',
  'Inauguración de la estación superficial Chabacano',
  'Metro Chabacano, Vista Alegre',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13562, 19.40918), 4326)::geography,
  '1975-10-20T12:00:00Z'::timestamptz,
  'El tren número 8 cerró sus puertas e inició su recorrido fatal desde Chabacano. Por razones que se debatirían ampliamente, el conductor interpretó erróneamente las señales. El tren aceleró sin aplicar los frenos.',
  'La fatídica salida del tren No. 8 desde el andén',
  'Metro Chabacano, Cuauhtémoc',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13562, 19.40918), 4326)::geography,
  '1994-07-20T12:00:00Z'::timestamptz,
  'Se completaron las obras que interconectaron las líneas 8 y 9 con la Línea 2 en Chabacano, convirtiéndola en un mega-centro de transferencia de tres niveles.',
  'Conclusión del mega-nodo de transbordo de tres líneas',
  'Metro Chabacano, Vista Alegre',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1369, 19.40087), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'La estación Viaducto fue inaugurada sobre la intersección del Viaducto Río de la Piedad y la Calzada de Tlalpan, integrando el sistema mediante pilares y puentes peatonales.',
  'Inauguración de la estación puente Metro Viaducto',
  'Metro Viaducto, Álamos',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1369, 19.40087), 4326)::geography,
  '1975-10-20T12:00:00Z'::timestamptz,
  'El tren número 8 que venía de Chabacano a unos 70 km/h se estrelló violentamente por alcance contra el convoy 10 detenido en Viaducto. El siniestro más letal de la red, con al menos 31 muertos.',
  'El histórico y mortífero choque de trenes en Viaducto',
  'Metro Viaducto, Santa Anita',
  '5'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1369, 19.40087), 4326)::geography,
  '1976-01-01T12:00:00Z'::timestamptz,
  'Como consecuencia del choque en Viaducto, el STC tomó la decisión de erradicar los sistemas de conducción exclusivamente manuales e implementar el Piloto Automático y cajas negras en cada cabina.',
  'Implementación del Piloto Automático y cajas negras en el STC',
  'Metro Viaducto, Iztacalco',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13781, 19.39521), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'Se inauguró la estación Xola. Lance Wyman seleccionó el dibujo de una palmera datilera como logotipo, inmortalizando el gigantesco árbol que dominaba el paisaje aledaño.',
  'Inauguración de la estación Metro Xola y su iconografía',
  'Metro Xola, Álamos',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13781, 19.39521), 4326)::geography,
  '1920-01-01T12:00:00Z'::timestamptz,
  'El dueño de una casona en los terrenos de la futura Xola tomó la decisión de trasladar desde Guadalajara y plantar una majestuosa palmera datilera en su jardín.',
  'Plantación de la icónica palmera monumental de Xola',
  'Metro Xola, Benito Juárez',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'DEATH'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13781, 19.39521), 4326)::geography,
  '2022-04-24T12:00:00Z'::timestamptz,
  'Tras más de cien años, la legendaria palmera de Xola enfermó mortalmente por una plaga de hongos. Las autoridades emitieron el veredicto de tala por riesgo de colapso sobre los carriles.',
  'Tala por enfermedad del árbol histórico de la estación',
  'Metro Xola, Moderna',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13896, 19.38758), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'La estación Villa de Cortés fue puesta en funcionamiento. Su diseño se distinguió por estar incrustada en un nivel elevado sobre los puentes vehiculares.',
  'Inauguración de la estación Metro Villa de Cortés',
  'Metro Villa de Cortés, Villa de Cortés',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13896, 19.38758), 4326)::geography,
  '1969-01-01T12:00:00Z'::timestamptz,
  'Los planificadores tomaron la decisión de emplear el dibujo de un yelmo de soldado conquistador español para la iconografía de la estación, homenajeando a Hernán Cortés y el encuentro con Moctezuma.',
  'Adopción de iconografía alusiva al encuentro de dos mundos',
  'Metro Villa de Cortés, Benito Juárez',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13896, 19.38758), 4326)::geography,
  '2019-09-13T12:00:00Z'::timestamptz,
  'Durante obras de remodelación, un automóvil que circulaba a exceso de velocidad colisionó catastróficamente contra los macizos de protección bajo los andenes. Dos personas fallecieron.',
  'Accidente fatal en zona de obras bajo el puente de la estación',
  'Metro Villa de Cortés, Benito Juárez',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13953, 19.34376), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'La estación terminal Tasqueña abrió sus puertas, finalizando el gran trazo sur original de la Línea 2. La terminal se proyectó como la principal compuerta multimodal de entrada y salida para millones de personas del sur.',
  'Inauguración de la gran terminal multimodal Metro Tasqueña',
  'Metro Tasqueña, Campestre Churubusco',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13953, 19.34376), 4326)::geography,
  '1972-01-01T12:00:00Z'::timestamptz,
  'La estación Tasqueña tiene el honor de haber sido escenario del primer gran accidente mecánico documentado del STC. Un convoy perdió adherencia y sufrió un violento descarrilamiento en las vías de maniobra.',
  'El histórico primer descarrilamiento de trenes en la red del STC',
  'Metro Tasqueña, Coyoacán',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.13953, 19.34376), 4326)::geography,
  '1986-08-01T12:00:00Z'::timestamptz,
  'El gobierno inauguró el sistema del Tren Ligero eléctrico directamente a los andenes de Tasqueña, elevándola al estatus de Mega-Hub Metropolitano hacia Tlalpan y Xochimilco.',
  'Interconexión y consolidación de la central del Tren Ligero',
  'Metro Tasqueña, Campestre Churubusco',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14019, 19.37953), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'Se inauguró la estación Nativitas, nombrada en referencia al antiguo templo parroquial y a la herencia lacustre que caracterizó a esta franja del Valle de México.',
  'Inauguración de la estación Metro Nativitas',
  'Metro Nativitas, Nativitas',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELOCATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14019, 19.37953), 4326)::geography,
  '1965-01-01T12:00:00Z'::timestamptz,
  'La legendaria Hacienda del Lago sufrió una fase de deterioro y posterior demolición. Los terrenos fueron adquiridos para centros comerciales y las rutas del STC Metro.',
  'Desmantelamiento y demolición de la Hacienda del Lago',
  'Metro Nativitas, Benito Juárez',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14019, 19.37953), 4326)::geography,
  '2003-09-03T12:00:00Z'::timestamptz,
  'Las autoridades tomaron posesión de una casa-habitación y la inauguraron como el Centro Cultural Nativitas, preservando la vitalidad artística del barrio frente a la gentrificación.',
  'Fundación del Centro Cultural Nativitas',
  'Metro Nativitas, Nativitas',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14157, 19.36992), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'La estación Portales fue inaugurada para dotar de transporte rápido a una de las colonias más efervescentes y tradicionalmente populares del sur de la Ciudad de México.',
  'Inauguración de la estación comercial Metro Portales',
  'Metro Portales, Portales Norte',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'RELOCATION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14157, 19.36992), 4326)::geography,
  '1950-01-01T12:00:00Z'::timestamptz,
  'El área que hoy envuelve a Portales estaba dominada por inmensas industrias de manufactura de tabique. La expansión urbana empujó a estas fábricas hacia las periferias del Estado de México.',
  'Erradicación y traslado de las fábricas ladrilleras históricas',
  'Metro Portales, Portales Sur',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14157, 19.36992), 4326)::geography,
  '1957-01-01T12:00:00Z'::timestamptz,
  'Años antes de la excavación de la estación, se inauguró el legendario Mercado de Portales. Cuando el Metro comenzó a operar, ambos se alimentaron mutuamente forjando un ecosistema comercial indisoluble.',
  'Consolidación del legendario Mercado de Portales',
  'Metro Portales, Benito Juárez',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1429, 19.36198), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'Se inauguró la estación Ermita, ubicada en la intersección del Eje 8 Sur y la Calzada de Tlalpan. Su nomenclatura recoge la figura de una ermita colonial que daba posada a los viajeros.',
  'Inauguración de la estación Metro Ermita',
  'Metro Ermita, Ermita',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1429, 19.36198), 4326)::geography,
  '1986-01-01T12:00:00Z'::timestamptz,
  'Una pesada losa de concreto del techo de la estación Ermita se desprendió e impactó contra el techo de un vagón que arribaba. Afortunadamente no se reportaron víctimas fatales.',
  'Colapso masivo de losa de techo sobre tren de pasajeros',
  'Metro Ermita, Benito Juárez',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'ACCIDENT'::event_type,
  ST_SetSRID(ST_MakePoint(-99.1429, 19.36198), 4326)::geography,
  '1995-06-05T12:00:00Z'::timestamptz,
  'Dos trenes chocaron violentamente en Ermita. Las indagatorias revelaron que un operador desactivó el Piloto Automático y manejó en modo manual libre, suprimiendo las distancias de seguridad.',
  'Choque aparatoso de convoyes por omisión de protocolo',
  'Metro Ermita, Miravalle',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14501, 19.35324), 4326)::geography,
  '1970-08-01T12:00:00Z'::timestamptz,
  'La estación General Anaya fue inaugurada como la penúltima parada del trazo de la Línea Azul al sur, ubicada en los bordes de Coyoacán.',
  'Inauguración de la estación Metro General Anaya',
  'Metro General Anaya, Churubusco',
  '3'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'MAJOR_DECISION'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14501, 19.35324), 4326)::geography,
  '1969-01-01T12:00:00Z'::timestamptz,
  'La Comisión de Nomenclatura del STC emitió el fallo para dedicar el nombre al General Pedro María Anaya, héroe de la resistencia durante la invasión estadounidense de 1847 en Churubusco.',
  'Adjudicación como homenaje cívico al héroe de Churubusco',
  'Metro General Anaya, Coyoacán',
  '2'::emotional_intensity,
  true,
  'approved'::event_status
);

INSERT INTO events (event_type, location, occurred_at, description, title, location_label, emotional_intensity, is_anonymous, status)
VALUES (
  'NEW_BEGINNING'::event_type,
  ST_SetSRID(ST_MakePoint(-99.14501, 19.35324), 4326)::geography,
  '2023-10-28T12:00:00Z'::timestamptz,
  'El Centro de Convenciones Churubusco se transformó en sede masiva de convenciones juveniles. Eventos como el Anime Fest congregan a más de 8,000 asistentes que saturan los andenes del Metro General Anaya.',
  'Consolidación como acceso de convenciones masivas y el Anime Fest',
  'Metro General Anaya, Churubusco',
  '4'::emotional_intensity,
  true,
  'approved'::event_status
);
